// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: common.proto

package ProtoMsgData;

public final class Common {
  private Common() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  public enum AttrType
      implements com.google.protobuf.ProtocolMessageEnum {
    Attr_Level(0, 1),
    Attr_Vouchers(1, 2),
    Attr_Balance(2, 3),
    Attr_Recharge(3, 4),
    Attr_Max(4, 20),
    ;
    
    public static final int Attr_Level_VALUE = 1;
    public static final int Attr_Vouchers_VALUE = 2;
    public static final int Attr_Balance_VALUE = 3;
    public static final int Attr_Recharge_VALUE = 4;
    public static final int Attr_Max_VALUE = 20;
    
    
    public final int getNumber() { return value; }
    
    public static AttrType valueOf(int value) {
      switch (value) {
        case 1: return Attr_Level;
        case 2: return Attr_Vouchers;
        case 3: return Attr_Balance;
        case 4: return Attr_Recharge;
        case 20: return Attr_Max;
        default: return null;
      }
    }
    
    public static com.google.protobuf.Internal.EnumLiteMap<AttrType>
        internalGetValueMap() {
      return internalValueMap;
    }
    private static com.google.protobuf.Internal.EnumLiteMap<AttrType>
        internalValueMap =
          new com.google.protobuf.Internal.EnumLiteMap<AttrType>() {
            public AttrType findValueByNumber(int number) {
              return AttrType.valueOf(number);
            }
          };
    
    public final com.google.protobuf.Descriptors.EnumValueDescriptor
        getValueDescriptor() {
      return getDescriptor().getValues().get(index);
    }
    public final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptorForType() {
      return getDescriptor();
    }
    public static final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptor() {
      return ProtoMsgData.Common.getDescriptor().getEnumTypes().get(0);
    }
    
    private static final AttrType[] VALUES = {
      Attr_Level, Attr_Vouchers, Attr_Balance, Attr_Recharge, Attr_Max, 
    };
    
    public static AttrType valueOf(
        com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
      if (desc.getType() != getDescriptor()) {
        throw new java.lang.IllegalArgumentException(
          "EnumValueDescriptor is not for this type.");
      }
      return VALUES[desc.getIndex()];
    }
    
    private final int index;
    private final int value;
    
    private AttrType(int index, int value) {
      this.index = index;
      this.value = value;
    }
    
    // @@protoc_insertion_point(enum_scope:ProtoMsgData.AttrType)
  }
  
  public enum ErrorCode
      implements com.google.protobuf.ProtocolMessageEnum {
    EC_Default(0, 0),
    EC_Address(1, 1),
    EC_Price(2, 2),
    EC_Area(3, 3),
    EC_Num(4, 4),
    EC_Person(5, 5),
    EC_Hour(6, 6),
    EC_Business(7, 7),
    EC_Code_Error(8, 8),
    EC_Code_Timeout(9, 9),
    EC_Code_Used(10, 10),
    EC_Balance_Lack(11, 11),
    ;
    
    public static final int EC_Default_VALUE = 0;
    public static final int EC_Address_VALUE = 1;
    public static final int EC_Price_VALUE = 2;
    public static final int EC_Area_VALUE = 3;
    public static final int EC_Num_VALUE = 4;
    public static final int EC_Person_VALUE = 5;
    public static final int EC_Hour_VALUE = 6;
    public static final int EC_Business_VALUE = 7;
    public static final int EC_Code_Error_VALUE = 8;
    public static final int EC_Code_Timeout_VALUE = 9;
    public static final int EC_Code_Used_VALUE = 10;
    public static final int EC_Balance_Lack_VALUE = 11;
    
    
    public final int getNumber() { return value; }
    
    public static ErrorCode valueOf(int value) {
      switch (value) {
        case 0: return EC_Default;
        case 1: return EC_Address;
        case 2: return EC_Price;
        case 3: return EC_Area;
        case 4: return EC_Num;
        case 5: return EC_Person;
        case 6: return EC_Hour;
        case 7: return EC_Business;
        case 8: return EC_Code_Error;
        case 9: return EC_Code_Timeout;
        case 10: return EC_Code_Used;
        case 11: return EC_Balance_Lack;
        default: return null;
      }
    }
    
    public static com.google.protobuf.Internal.EnumLiteMap<ErrorCode>
        internalGetValueMap() {
      return internalValueMap;
    }
    private static com.google.protobuf.Internal.EnumLiteMap<ErrorCode>
        internalValueMap =
          new com.google.protobuf.Internal.EnumLiteMap<ErrorCode>() {
            public ErrorCode findValueByNumber(int number) {
              return ErrorCode.valueOf(number);
            }
          };
    
    public final com.google.protobuf.Descriptors.EnumValueDescriptor
        getValueDescriptor() {
      return getDescriptor().getValues().get(index);
    }
    public final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptorForType() {
      return getDescriptor();
    }
    public static final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptor() {
      return ProtoMsgData.Common.getDescriptor().getEnumTypes().get(1);
    }
    
    private static final ErrorCode[] VALUES = {
      EC_Default, EC_Address, EC_Price, EC_Area, EC_Num, EC_Person, EC_Hour, EC_Business, EC_Code_Error, EC_Code_Timeout, EC_Code_Used, EC_Balance_Lack, 
    };
    
    public static ErrorCode valueOf(
        com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
      if (desc.getType() != getDescriptor()) {
        throw new java.lang.IllegalArgumentException(
          "EnumValueDescriptor is not for this type.");
      }
      return VALUES[desc.getIndex()];
    }
    
    private final int index;
    private final int value;
    
    private ErrorCode(int index, int value) {
      this.index = index;
      this.value = value;
    }
    
    // @@protoc_insertion_point(enum_scope:ProtoMsgData.ErrorCode)
  }
  
  public interface AckUpdateAttrValOrBuilder
      extends com.google.protobuf.MessageOrBuilder {
    
    // required .ProtoMsgData.AttrType attrtype = 1;
    boolean hasAttrtype();
    ProtoMsgData.Common.AttrType getAttrtype();
    
    // required uint32 attrval = 2;
    boolean hasAttrval();
    int getAttrval();
  }
  public static final class AckUpdateAttrVal extends
      com.google.protobuf.GeneratedMessage
      implements AckUpdateAttrValOrBuilder {
    // Use AckUpdateAttrVal.newBuilder() to construct.
    private AckUpdateAttrVal(Builder builder) {
      super(builder);
    }
    private AckUpdateAttrVal(boolean noInit) {}
    
    private static final AckUpdateAttrVal defaultInstance;
    public static AckUpdateAttrVal getDefaultInstance() {
      return defaultInstance;
    }
    
    public AckUpdateAttrVal getDefaultInstanceForType() {
      return defaultInstance;
    }
    
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return ProtoMsgData.Common.internal_static_ProtoMsgData_AckUpdateAttrVal_descriptor;
    }
    
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return ProtoMsgData.Common.internal_static_ProtoMsgData_AckUpdateAttrVal_fieldAccessorTable;
    }
    
    private int bitField0_;
    // required .ProtoMsgData.AttrType attrtype = 1;
    public static final int ATTRTYPE_FIELD_NUMBER = 1;
    private ProtoMsgData.Common.AttrType attrtype_;
    public boolean hasAttrtype() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    public ProtoMsgData.Common.AttrType getAttrtype() {
      return attrtype_;
    }
    
    // required uint32 attrval = 2;
    public static final int ATTRVAL_FIELD_NUMBER = 2;
    private int attrval_;
    public boolean hasAttrval() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    public int getAttrval() {
      return attrval_;
    }
    
    private void initFields() {
      attrtype_ = ProtoMsgData.Common.AttrType.Attr_Level;
      attrval_ = 0;
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;
      
      if (!hasAttrtype()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasAttrval()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }
    
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeEnum(1, attrtype_.getNumber());
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeUInt32(2, attrval_);
      }
      getUnknownFields().writeTo(output);
    }
    
    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;
    
      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeEnumSize(1, attrtype_.getNumber());
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeUInt32Size(2, attrval_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }
    
    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }
    
    public static ProtoMsgData.Common.AckUpdateAttrVal parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static ProtoMsgData.Common.AckUpdateAttrVal parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static ProtoMsgData.Common.AckUpdateAttrVal parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static ProtoMsgData.Common.AckUpdateAttrVal parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static ProtoMsgData.Common.AckUpdateAttrVal parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static ProtoMsgData.Common.AckUpdateAttrVal parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    public static ProtoMsgData.Common.AckUpdateAttrVal parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static ProtoMsgData.Common.AckUpdateAttrVal parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input, extensionRegistry)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static ProtoMsgData.Common.AckUpdateAttrVal parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static ProtoMsgData.Common.AckUpdateAttrVal parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    
    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(ProtoMsgData.Common.AckUpdateAttrVal prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }
    
    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements ProtoMsgData.Common.AckUpdateAttrValOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return ProtoMsgData.Common.internal_static_ProtoMsgData_AckUpdateAttrVal_descriptor;
      }
      
      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return ProtoMsgData.Common.internal_static_ProtoMsgData_AckUpdateAttrVal_fieldAccessorTable;
      }
      
      // Construct using ProtoMsgData.Common.AckUpdateAttrVal.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }
      
      private Builder(BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }
      
      public Builder clear() {
        super.clear();
        attrtype_ = ProtoMsgData.Common.AttrType.Attr_Level;
        bitField0_ = (bitField0_ & ~0x00000001);
        attrval_ = 0;
        bitField0_ = (bitField0_ & ~0x00000002);
        return this;
      }
      
      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }
      
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return ProtoMsgData.Common.AckUpdateAttrVal.getDescriptor();
      }
      
      public ProtoMsgData.Common.AckUpdateAttrVal getDefaultInstanceForType() {
        return ProtoMsgData.Common.AckUpdateAttrVal.getDefaultInstance();
      }
      
      public ProtoMsgData.Common.AckUpdateAttrVal build() {
        ProtoMsgData.Common.AckUpdateAttrVal result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }
      
      private ProtoMsgData.Common.AckUpdateAttrVal buildParsed()
          throws com.google.protobuf.InvalidProtocolBufferException {
        ProtoMsgData.Common.AckUpdateAttrVal result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(
            result).asInvalidProtocolBufferException();
        }
        return result;
      }
      
      public ProtoMsgData.Common.AckUpdateAttrVal buildPartial() {
        ProtoMsgData.Common.AckUpdateAttrVal result = new ProtoMsgData.Common.AckUpdateAttrVal(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.attrtype_ = attrtype_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.attrval_ = attrval_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }
      
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof ProtoMsgData.Common.AckUpdateAttrVal) {
          return mergeFrom((ProtoMsgData.Common.AckUpdateAttrVal)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }
      
      public Builder mergeFrom(ProtoMsgData.Common.AckUpdateAttrVal other) {
        if (other == ProtoMsgData.Common.AckUpdateAttrVal.getDefaultInstance()) return this;
        if (other.hasAttrtype()) {
          setAttrtype(other.getAttrtype());
        }
        if (other.hasAttrval()) {
          setAttrval(other.getAttrval());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }
      
      public final boolean isInitialized() {
        if (!hasAttrtype()) {
          
          return false;
        }
        if (!hasAttrval()) {
          
          return false;
        }
        return true;
      }
      
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder(
            this.getUnknownFields());
        while (true) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              this.setUnknownFields(unknownFields.build());
              onChanged();
              return this;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                this.setUnknownFields(unknownFields.build());
                onChanged();
                return this;
              }
              break;
            }
            case 8: {
              int rawValue = input.readEnum();
              ProtoMsgData.Common.AttrType value = ProtoMsgData.Common.AttrType.valueOf(rawValue);
              if (value == null) {
                unknownFields.mergeVarintField(1, rawValue);
              } else {
                bitField0_ |= 0x00000001;
                attrtype_ = value;
              }
              break;
            }
            case 16: {
              bitField0_ |= 0x00000002;
              attrval_ = input.readUInt32();
              break;
            }
          }
        }
      }
      
      private int bitField0_;
      
      // required .ProtoMsgData.AttrType attrtype = 1;
      private ProtoMsgData.Common.AttrType attrtype_ = ProtoMsgData.Common.AttrType.Attr_Level;
      public boolean hasAttrtype() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      public ProtoMsgData.Common.AttrType getAttrtype() {
        return attrtype_;
      }
      public Builder setAttrtype(ProtoMsgData.Common.AttrType value) {
        if (value == null) {
          throw new NullPointerException();
        }
        bitField0_ |= 0x00000001;
        attrtype_ = value;
        onChanged();
        return this;
      }
      public Builder clearAttrtype() {
        bitField0_ = (bitField0_ & ~0x00000001);
        attrtype_ = ProtoMsgData.Common.AttrType.Attr_Level;
        onChanged();
        return this;
      }
      
      // required uint32 attrval = 2;
      private int attrval_ ;
      public boolean hasAttrval() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      public int getAttrval() {
        return attrval_;
      }
      public Builder setAttrval(int value) {
        bitField0_ |= 0x00000002;
        attrval_ = value;
        onChanged();
        return this;
      }
      public Builder clearAttrval() {
        bitField0_ = (bitField0_ & ~0x00000002);
        attrval_ = 0;
        onChanged();
        return this;
      }
      
      // @@protoc_insertion_point(builder_scope:ProtoMsgData.AckUpdateAttrVal)
    }
    
    static {
      defaultInstance = new AckUpdateAttrVal(true);
      defaultInstance.initFields();
    }
    
    // @@protoc_insertion_point(class_scope:ProtoMsgData.AckUpdateAttrVal)
  }
  
  public interface AckErrorCodeOrBuilder
      extends com.google.protobuf.MessageOrBuilder {
    
    // required .ProtoMsgData.ErrorCode errorcode = 1;
    boolean hasErrorcode();
    ProtoMsgData.Common.ErrorCode getErrorcode();
  }
  public static final class AckErrorCode extends
      com.google.protobuf.GeneratedMessage
      implements AckErrorCodeOrBuilder {
    // Use AckErrorCode.newBuilder() to construct.
    private AckErrorCode(Builder builder) {
      super(builder);
    }
    private AckErrorCode(boolean noInit) {}
    
    private static final AckErrorCode defaultInstance;
    public static AckErrorCode getDefaultInstance() {
      return defaultInstance;
    }
    
    public AckErrorCode getDefaultInstanceForType() {
      return defaultInstance;
    }
    
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return ProtoMsgData.Common.internal_static_ProtoMsgData_AckErrorCode_descriptor;
    }
    
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return ProtoMsgData.Common.internal_static_ProtoMsgData_AckErrorCode_fieldAccessorTable;
    }
    
    private int bitField0_;
    // required .ProtoMsgData.ErrorCode errorcode = 1;
    public static final int ERRORCODE_FIELD_NUMBER = 1;
    private ProtoMsgData.Common.ErrorCode errorcode_;
    public boolean hasErrorcode() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    public ProtoMsgData.Common.ErrorCode getErrorcode() {
      return errorcode_;
    }
    
    private void initFields() {
      errorcode_ = ProtoMsgData.Common.ErrorCode.EC_Default;
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;
      
      if (!hasErrorcode()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }
    
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeEnum(1, errorcode_.getNumber());
      }
      getUnknownFields().writeTo(output);
    }
    
    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;
    
      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeEnumSize(1, errorcode_.getNumber());
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }
    
    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }
    
    public static ProtoMsgData.Common.AckErrorCode parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static ProtoMsgData.Common.AckErrorCode parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static ProtoMsgData.Common.AckErrorCode parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static ProtoMsgData.Common.AckErrorCode parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static ProtoMsgData.Common.AckErrorCode parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static ProtoMsgData.Common.AckErrorCode parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    public static ProtoMsgData.Common.AckErrorCode parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static ProtoMsgData.Common.AckErrorCode parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input, extensionRegistry)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static ProtoMsgData.Common.AckErrorCode parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static ProtoMsgData.Common.AckErrorCode parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    
    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(ProtoMsgData.Common.AckErrorCode prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }
    
    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements ProtoMsgData.Common.AckErrorCodeOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return ProtoMsgData.Common.internal_static_ProtoMsgData_AckErrorCode_descriptor;
      }
      
      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return ProtoMsgData.Common.internal_static_ProtoMsgData_AckErrorCode_fieldAccessorTable;
      }
      
      // Construct using ProtoMsgData.Common.AckErrorCode.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }
      
      private Builder(BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }
      
      public Builder clear() {
        super.clear();
        errorcode_ = ProtoMsgData.Common.ErrorCode.EC_Default;
        bitField0_ = (bitField0_ & ~0x00000001);
        return this;
      }
      
      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }
      
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return ProtoMsgData.Common.AckErrorCode.getDescriptor();
      }
      
      public ProtoMsgData.Common.AckErrorCode getDefaultInstanceForType() {
        return ProtoMsgData.Common.AckErrorCode.getDefaultInstance();
      }
      
      public ProtoMsgData.Common.AckErrorCode build() {
        ProtoMsgData.Common.AckErrorCode result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }
      
      private ProtoMsgData.Common.AckErrorCode buildParsed()
          throws com.google.protobuf.InvalidProtocolBufferException {
        ProtoMsgData.Common.AckErrorCode result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(
            result).asInvalidProtocolBufferException();
        }
        return result;
      }
      
      public ProtoMsgData.Common.AckErrorCode buildPartial() {
        ProtoMsgData.Common.AckErrorCode result = new ProtoMsgData.Common.AckErrorCode(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.errorcode_ = errorcode_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }
      
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof ProtoMsgData.Common.AckErrorCode) {
          return mergeFrom((ProtoMsgData.Common.AckErrorCode)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }
      
      public Builder mergeFrom(ProtoMsgData.Common.AckErrorCode other) {
        if (other == ProtoMsgData.Common.AckErrorCode.getDefaultInstance()) return this;
        if (other.hasErrorcode()) {
          setErrorcode(other.getErrorcode());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }
      
      public final boolean isInitialized() {
        if (!hasErrorcode()) {
          
          return false;
        }
        return true;
      }
      
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder(
            this.getUnknownFields());
        while (true) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              this.setUnknownFields(unknownFields.build());
              onChanged();
              return this;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                this.setUnknownFields(unknownFields.build());
                onChanged();
                return this;
              }
              break;
            }
            case 8: {
              int rawValue = input.readEnum();
              ProtoMsgData.Common.ErrorCode value = ProtoMsgData.Common.ErrorCode.valueOf(rawValue);
              if (value == null) {
                unknownFields.mergeVarintField(1, rawValue);
              } else {
                bitField0_ |= 0x00000001;
                errorcode_ = value;
              }
              break;
            }
          }
        }
      }
      
      private int bitField0_;
      
      // required .ProtoMsgData.ErrorCode errorcode = 1;
      private ProtoMsgData.Common.ErrorCode errorcode_ = ProtoMsgData.Common.ErrorCode.EC_Default;
      public boolean hasErrorcode() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      public ProtoMsgData.Common.ErrorCode getErrorcode() {
        return errorcode_;
      }
      public Builder setErrorcode(ProtoMsgData.Common.ErrorCode value) {
        if (value == null) {
          throw new NullPointerException();
        }
        bitField0_ |= 0x00000001;
        errorcode_ = value;
        onChanged();
        return this;
      }
      public Builder clearErrorcode() {
        bitField0_ = (bitField0_ & ~0x00000001);
        errorcode_ = ProtoMsgData.Common.ErrorCode.EC_Default;
        onChanged();
        return this;
      }
      
      // @@protoc_insertion_point(builder_scope:ProtoMsgData.AckErrorCode)
    }
    
    static {
      defaultInstance = new AckErrorCode(true);
      defaultInstance.initFields();
    }
    
    // @@protoc_insertion_point(class_scope:ProtoMsgData.AckErrorCode)
  }
  
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_ProtoMsgData_AckUpdateAttrVal_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_ProtoMsgData_AckUpdateAttrVal_fieldAccessorTable;
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_ProtoMsgData_AckErrorCode_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_ProtoMsgData_AckErrorCode_fieldAccessorTable;
  
  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\014common.proto\022\014ProtoMsgData\"M\n\020AckUpdat" +
      "eAttrVal\022(\n\010attrtype\030\001 \002(\0162\026.ProtoMsgDat" +
      "a.AttrType\022\017\n\007attrval\030\002 \002(\r\":\n\014AckErrorC" +
      "ode\022*\n\terrorcode\030\001 \002(\0162\027.ProtoMsgData.Er" +
      "rorCode*`\n\010AttrType\022\016\n\nAttr_Level\020\001\022\021\n\rA" +
      "ttr_Vouchers\020\002\022\020\n\014Attr_Balance\020\003\022\021\n\rAttr" +
      "_Recharge\020\004\022\014\n\010Attr_Max\020\024*\316\001\n\tErrorCode\022" +
      "\016\n\nEC_Default\020\000\022\016\n\nEC_Address\020\001\022\014\n\010EC_Pr" +
      "ice\020\002\022\013\n\007EC_Area\020\003\022\n\n\006EC_Num\020\004\022\r\n\tEC_Per" +
      "son\020\005\022\013\n\007EC_Hour\020\006\022\017\n\013EC_Business\020\007\022\021\n\rE",
      "C_Code_Error\020\010\022\023\n\017EC_Code_Timeout\020\t\022\020\n\014E" +
      "C_Code_Used\020\n\022\023\n\017EC_Balance_Lack\020\013"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
      new com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner() {
        public com.google.protobuf.ExtensionRegistry assignDescriptors(
            com.google.protobuf.Descriptors.FileDescriptor root) {
          descriptor = root;
          internal_static_ProtoMsgData_AckUpdateAttrVal_descriptor =
            getDescriptor().getMessageTypes().get(0);
          internal_static_ProtoMsgData_AckUpdateAttrVal_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_ProtoMsgData_AckUpdateAttrVal_descriptor,
              new java.lang.String[] { "Attrtype", "Attrval", },
              ProtoMsgData.Common.AckUpdateAttrVal.class,
              ProtoMsgData.Common.AckUpdateAttrVal.Builder.class);
          internal_static_ProtoMsgData_AckErrorCode_descriptor =
            getDescriptor().getMessageTypes().get(1);
          internal_static_ProtoMsgData_AckErrorCode_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_ProtoMsgData_AckErrorCode_descriptor,
              new java.lang.String[] { "Errorcode", },
              ProtoMsgData.Common.AckErrorCode.class,
              ProtoMsgData.Common.AckErrorCode.Builder.class);
          return null;
        }
      };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
  }
  
  // @@protoc_insertion_point(outer_class_scope)
}
