// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: synconfig.proto

package ProtoMsgData;

public final class Synconfig {
  private Synconfig() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  public interface BusinessConfigOrBuilder
      extends com.google.protobuf.MessageOrBuilder {
    
    // required uint32 type = 1;
    boolean hasType();
    int getType();
    
    // required uint32 id = 2;
    boolean hasId();
    int getId();
    
    // required string price = 3;
    boolean hasPrice();
    String getPrice();
    
    // required string disprice = 4;
    boolean hasDisprice();
    String getDisprice();
    
    // required string person = 5;
    boolean hasPerson();
    String getPerson();
  }
  public static final class BusinessConfig extends
      com.google.protobuf.GeneratedMessage
      implements BusinessConfigOrBuilder {
    // Use BusinessConfig.newBuilder() to construct.
    private BusinessConfig(Builder builder) {
      super(builder);
    }
    private BusinessConfig(boolean noInit) {}
    
    private static final BusinessConfig defaultInstance;
    public static BusinessConfig getDefaultInstance() {
      return defaultInstance;
    }
    
    public BusinessConfig getDefaultInstanceForType() {
      return defaultInstance;
    }
    
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return ProtoMsgData.Synconfig.internal_static_ProtoMsgData_BusinessConfig_descriptor;
    }
    
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return ProtoMsgData.Synconfig.internal_static_ProtoMsgData_BusinessConfig_fieldAccessorTable;
    }
    
    private int bitField0_;
    // required uint32 type = 1;
    public static final int TYPE_FIELD_NUMBER = 1;
    private int type_;
    public boolean hasType() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    public int getType() {
      return type_;
    }
    
    // required uint32 id = 2;
    public static final int ID_FIELD_NUMBER = 2;
    private int id_;
    public boolean hasId() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    public int getId() {
      return id_;
    }
    
    // required string price = 3;
    public static final int PRICE_FIELD_NUMBER = 3;
    private java.lang.Object price_;
    public boolean hasPrice() {
      return ((bitField0_ & 0x00000004) == 0x00000004);
    }
    public String getPrice() {
      java.lang.Object ref = price_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        if (com.google.protobuf.Internal.isValidUtf8(bs)) {
          price_ = s;
        }
        return s;
      }
    }
    private com.google.protobuf.ByteString getPriceBytes() {
      java.lang.Object ref = price_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8((String) ref);
        price_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    
    // required string disprice = 4;
    public static final int DISPRICE_FIELD_NUMBER = 4;
    private java.lang.Object disprice_;
    public boolean hasDisprice() {
      return ((bitField0_ & 0x00000008) == 0x00000008);
    }
    public String getDisprice() {
      java.lang.Object ref = disprice_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        if (com.google.protobuf.Internal.isValidUtf8(bs)) {
          disprice_ = s;
        }
        return s;
      }
    }
    private com.google.protobuf.ByteString getDispriceBytes() {
      java.lang.Object ref = disprice_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8((String) ref);
        disprice_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    
    // required string person = 5;
    public static final int PERSON_FIELD_NUMBER = 5;
    private java.lang.Object person_;
    public boolean hasPerson() {
      return ((bitField0_ & 0x00000010) == 0x00000010);
    }
    public String getPerson() {
      java.lang.Object ref = person_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        if (com.google.protobuf.Internal.isValidUtf8(bs)) {
          person_ = s;
        }
        return s;
      }
    }
    private com.google.protobuf.ByteString getPersonBytes() {
      java.lang.Object ref = person_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8((String) ref);
        person_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    
    private void initFields() {
      type_ = 0;
      id_ = 0;
      price_ = "";
      disprice_ = "";
      person_ = "";
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;
      
      if (!hasType()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasId()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasPrice()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasDisprice()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasPerson()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }
    
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeUInt32(1, type_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeUInt32(2, id_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        output.writeBytes(3, getPriceBytes());
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        output.writeBytes(4, getDispriceBytes());
      }
      if (((bitField0_ & 0x00000010) == 0x00000010)) {
        output.writeBytes(5, getPersonBytes());
      }
      getUnknownFields().writeTo(output);
    }
    
    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;
    
      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeUInt32Size(1, type_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeUInt32Size(2, id_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(3, getPriceBytes());
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(4, getDispriceBytes());
      }
      if (((bitField0_ & 0x00000010) == 0x00000010)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(5, getPersonBytes());
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }
    
    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }
    
    public static ProtoMsgData.Synconfig.BusinessConfig parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static ProtoMsgData.Synconfig.BusinessConfig parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static ProtoMsgData.Synconfig.BusinessConfig parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static ProtoMsgData.Synconfig.BusinessConfig parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static ProtoMsgData.Synconfig.BusinessConfig parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static ProtoMsgData.Synconfig.BusinessConfig parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    public static ProtoMsgData.Synconfig.BusinessConfig parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static ProtoMsgData.Synconfig.BusinessConfig parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input, extensionRegistry)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static ProtoMsgData.Synconfig.BusinessConfig parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static ProtoMsgData.Synconfig.BusinessConfig parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    
    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(ProtoMsgData.Synconfig.BusinessConfig prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }
    
    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements ProtoMsgData.Synconfig.BusinessConfigOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return ProtoMsgData.Synconfig.internal_static_ProtoMsgData_BusinessConfig_descriptor;
      }
      
      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return ProtoMsgData.Synconfig.internal_static_ProtoMsgData_BusinessConfig_fieldAccessorTable;
      }
      
      // Construct using ProtoMsgData.Synconfig.BusinessConfig.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }
      
      private Builder(BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }
      
      public Builder clear() {
        super.clear();
        type_ = 0;
        bitField0_ = (bitField0_ & ~0x00000001);
        id_ = 0;
        bitField0_ = (bitField0_ & ~0x00000002);
        price_ = "";
        bitField0_ = (bitField0_ & ~0x00000004);
        disprice_ = "";
        bitField0_ = (bitField0_ & ~0x00000008);
        person_ = "";
        bitField0_ = (bitField0_ & ~0x00000010);
        return this;
      }
      
      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }
      
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return ProtoMsgData.Synconfig.BusinessConfig.getDescriptor();
      }
      
      public ProtoMsgData.Synconfig.BusinessConfig getDefaultInstanceForType() {
        return ProtoMsgData.Synconfig.BusinessConfig.getDefaultInstance();
      }
      
      public ProtoMsgData.Synconfig.BusinessConfig build() {
        ProtoMsgData.Synconfig.BusinessConfig result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }
      
      private ProtoMsgData.Synconfig.BusinessConfig buildParsed()
          throws com.google.protobuf.InvalidProtocolBufferException {
        ProtoMsgData.Synconfig.BusinessConfig result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(
            result).asInvalidProtocolBufferException();
        }
        return result;
      }
      
      public ProtoMsgData.Synconfig.BusinessConfig buildPartial() {
        ProtoMsgData.Synconfig.BusinessConfig result = new ProtoMsgData.Synconfig.BusinessConfig(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.type_ = type_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.id_ = id_;
        if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
          to_bitField0_ |= 0x00000004;
        }
        result.price_ = price_;
        if (((from_bitField0_ & 0x00000008) == 0x00000008)) {
          to_bitField0_ |= 0x00000008;
        }
        result.disprice_ = disprice_;
        if (((from_bitField0_ & 0x00000010) == 0x00000010)) {
          to_bitField0_ |= 0x00000010;
        }
        result.person_ = person_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }
      
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof ProtoMsgData.Synconfig.BusinessConfig) {
          return mergeFrom((ProtoMsgData.Synconfig.BusinessConfig)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }
      
      public Builder mergeFrom(ProtoMsgData.Synconfig.BusinessConfig other) {
        if (other == ProtoMsgData.Synconfig.BusinessConfig.getDefaultInstance()) return this;
        if (other.hasType()) {
          setType(other.getType());
        }
        if (other.hasId()) {
          setId(other.getId());
        }
        if (other.hasPrice()) {
          setPrice(other.getPrice());
        }
        if (other.hasDisprice()) {
          setDisprice(other.getDisprice());
        }
        if (other.hasPerson()) {
          setPerson(other.getPerson());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }
      
      public final boolean isInitialized() {
        if (!hasType()) {
          
          return false;
        }
        if (!hasId()) {
          
          return false;
        }
        if (!hasPrice()) {
          
          return false;
        }
        if (!hasDisprice()) {
          
          return false;
        }
        if (!hasPerson()) {
          
          return false;
        }
        return true;
      }
      
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder(
            this.getUnknownFields());
        while (true) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              this.setUnknownFields(unknownFields.build());
              onChanged();
              return this;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                this.setUnknownFields(unknownFields.build());
                onChanged();
                return this;
              }
              break;
            }
            case 8: {
              bitField0_ |= 0x00000001;
              type_ = input.readUInt32();
              break;
            }
            case 16: {
              bitField0_ |= 0x00000002;
              id_ = input.readUInt32();
              break;
            }
            case 26: {
              bitField0_ |= 0x00000004;
              price_ = input.readBytes();
              break;
            }
            case 34: {
              bitField0_ |= 0x00000008;
              disprice_ = input.readBytes();
              break;
            }
            case 42: {
              bitField0_ |= 0x00000010;
              person_ = input.readBytes();
              break;
            }
          }
        }
      }
      
      private int bitField0_;
      
      // required uint32 type = 1;
      private int type_ ;
      public boolean hasType() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      public int getType() {
        return type_;
      }
      public Builder setType(int value) {
        bitField0_ |= 0x00000001;
        type_ = value;
        onChanged();
        return this;
      }
      public Builder clearType() {
        bitField0_ = (bitField0_ & ~0x00000001);
        type_ = 0;
        onChanged();
        return this;
      }
      
      // required uint32 id = 2;
      private int id_ ;
      public boolean hasId() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      public int getId() {
        return id_;
      }
      public Builder setId(int value) {
        bitField0_ |= 0x00000002;
        id_ = value;
        onChanged();
        return this;
      }
      public Builder clearId() {
        bitField0_ = (bitField0_ & ~0x00000002);
        id_ = 0;
        onChanged();
        return this;
      }
      
      // required string price = 3;
      private java.lang.Object price_ = "";
      public boolean hasPrice() {
        return ((bitField0_ & 0x00000004) == 0x00000004);
      }
      public String getPrice() {
        java.lang.Object ref = price_;
        if (!(ref instanceof String)) {
          String s = ((com.google.protobuf.ByteString) ref).toStringUtf8();
          price_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      public Builder setPrice(String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000004;
        price_ = value;
        onChanged();
        return this;
      }
      public Builder clearPrice() {
        bitField0_ = (bitField0_ & ~0x00000004);
        price_ = getDefaultInstance().getPrice();
        onChanged();
        return this;
      }
      void setPrice(com.google.protobuf.ByteString value) {
        bitField0_ |= 0x00000004;
        price_ = value;
        onChanged();
      }
      
      // required string disprice = 4;
      private java.lang.Object disprice_ = "";
      public boolean hasDisprice() {
        return ((bitField0_ & 0x00000008) == 0x00000008);
      }
      public String getDisprice() {
        java.lang.Object ref = disprice_;
        if (!(ref instanceof String)) {
          String s = ((com.google.protobuf.ByteString) ref).toStringUtf8();
          disprice_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      public Builder setDisprice(String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000008;
        disprice_ = value;
        onChanged();
        return this;
      }
      public Builder clearDisprice() {
        bitField0_ = (bitField0_ & ~0x00000008);
        disprice_ = getDefaultInstance().getDisprice();
        onChanged();
        return this;
      }
      void setDisprice(com.google.protobuf.ByteString value) {
        bitField0_ |= 0x00000008;
        disprice_ = value;
        onChanged();
      }
      
      // required string person = 5;
      private java.lang.Object person_ = "";
      public boolean hasPerson() {
        return ((bitField0_ & 0x00000010) == 0x00000010);
      }
      public String getPerson() {
        java.lang.Object ref = person_;
        if (!(ref instanceof String)) {
          String s = ((com.google.protobuf.ByteString) ref).toStringUtf8();
          person_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      public Builder setPerson(String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000010;
        person_ = value;
        onChanged();
        return this;
      }
      public Builder clearPerson() {
        bitField0_ = (bitField0_ & ~0x00000010);
        person_ = getDefaultInstance().getPerson();
        onChanged();
        return this;
      }
      void setPerson(com.google.protobuf.ByteString value) {
        bitField0_ |= 0x00000010;
        person_ = value;
        onChanged();
      }
      
      // @@protoc_insertion_point(builder_scope:ProtoMsgData.BusinessConfig)
    }
    
    static {
      defaultInstance = new BusinessConfig(true);
      defaultInstance.initFields();
    }
    
    // @@protoc_insertion_point(class_scope:ProtoMsgData.BusinessConfig)
  }
  
  public interface AckSynConfigOrBuilder
      extends com.google.protobuf.MessageOrBuilder {
    
    // repeated .ProtoMsgData.BusinessConfig businessconfig = 1;
    java.util.List<ProtoMsgData.Synconfig.BusinessConfig> 
        getBusinessconfigList();
    ProtoMsgData.Synconfig.BusinessConfig getBusinessconfig(int index);
    int getBusinessconfigCount();
    java.util.List<? extends ProtoMsgData.Synconfig.BusinessConfigOrBuilder> 
        getBusinessconfigOrBuilderList();
    ProtoMsgData.Synconfig.BusinessConfigOrBuilder getBusinessconfigOrBuilder(
        int index);
  }
  public static final class AckSynConfig extends
      com.google.protobuf.GeneratedMessage
      implements AckSynConfigOrBuilder {
    // Use AckSynConfig.newBuilder() to construct.
    private AckSynConfig(Builder builder) {
      super(builder);
    }
    private AckSynConfig(boolean noInit) {}
    
    private static final AckSynConfig defaultInstance;
    public static AckSynConfig getDefaultInstance() {
      return defaultInstance;
    }
    
    public AckSynConfig getDefaultInstanceForType() {
      return defaultInstance;
    }
    
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return ProtoMsgData.Synconfig.internal_static_ProtoMsgData_AckSynConfig_descriptor;
    }
    
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return ProtoMsgData.Synconfig.internal_static_ProtoMsgData_AckSynConfig_fieldAccessorTable;
    }
    
    // repeated .ProtoMsgData.BusinessConfig businessconfig = 1;
    public static final int BUSINESSCONFIG_FIELD_NUMBER = 1;
    private java.util.List<ProtoMsgData.Synconfig.BusinessConfig> businessconfig_;
    public java.util.List<ProtoMsgData.Synconfig.BusinessConfig> getBusinessconfigList() {
      return businessconfig_;
    }
    public java.util.List<? extends ProtoMsgData.Synconfig.BusinessConfigOrBuilder> 
        getBusinessconfigOrBuilderList() {
      return businessconfig_;
    }
    public int getBusinessconfigCount() {
      return businessconfig_.size();
    }
    public ProtoMsgData.Synconfig.BusinessConfig getBusinessconfig(int index) {
      return businessconfig_.get(index);
    }
    public ProtoMsgData.Synconfig.BusinessConfigOrBuilder getBusinessconfigOrBuilder(
        int index) {
      return businessconfig_.get(index);
    }
    
    private void initFields() {
      businessconfig_ = java.util.Collections.emptyList();
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;
      
      for (int i = 0; i < getBusinessconfigCount(); i++) {
        if (!getBusinessconfig(i).isInitialized()) {
          memoizedIsInitialized = 0;
          return false;
        }
      }
      memoizedIsInitialized = 1;
      return true;
    }
    
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      for (int i = 0; i < businessconfig_.size(); i++) {
        output.writeMessage(1, businessconfig_.get(i));
      }
      getUnknownFields().writeTo(output);
    }
    
    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;
    
      size = 0;
      for (int i = 0; i < businessconfig_.size(); i++) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(1, businessconfig_.get(i));
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }
    
    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }
    
    public static ProtoMsgData.Synconfig.AckSynConfig parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static ProtoMsgData.Synconfig.AckSynConfig parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static ProtoMsgData.Synconfig.AckSynConfig parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static ProtoMsgData.Synconfig.AckSynConfig parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static ProtoMsgData.Synconfig.AckSynConfig parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static ProtoMsgData.Synconfig.AckSynConfig parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    public static ProtoMsgData.Synconfig.AckSynConfig parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static ProtoMsgData.Synconfig.AckSynConfig parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input, extensionRegistry)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static ProtoMsgData.Synconfig.AckSynConfig parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static ProtoMsgData.Synconfig.AckSynConfig parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    
    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(ProtoMsgData.Synconfig.AckSynConfig prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }
    
    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements ProtoMsgData.Synconfig.AckSynConfigOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return ProtoMsgData.Synconfig.internal_static_ProtoMsgData_AckSynConfig_descriptor;
      }
      
      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return ProtoMsgData.Synconfig.internal_static_ProtoMsgData_AckSynConfig_fieldAccessorTable;
      }
      
      // Construct using ProtoMsgData.Synconfig.AckSynConfig.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }
      
      private Builder(BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
          getBusinessconfigFieldBuilder();
        }
      }
      private static Builder create() {
        return new Builder();
      }
      
      public Builder clear() {
        super.clear();
        if (businessconfigBuilder_ == null) {
          businessconfig_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000001);
        } else {
          businessconfigBuilder_.clear();
        }
        return this;
      }
      
      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }
      
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return ProtoMsgData.Synconfig.AckSynConfig.getDescriptor();
      }
      
      public ProtoMsgData.Synconfig.AckSynConfig getDefaultInstanceForType() {
        return ProtoMsgData.Synconfig.AckSynConfig.getDefaultInstance();
      }
      
      public ProtoMsgData.Synconfig.AckSynConfig build() {
        ProtoMsgData.Synconfig.AckSynConfig result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }
      
      private ProtoMsgData.Synconfig.AckSynConfig buildParsed()
          throws com.google.protobuf.InvalidProtocolBufferException {
        ProtoMsgData.Synconfig.AckSynConfig result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(
            result).asInvalidProtocolBufferException();
        }
        return result;
      }
      
      public ProtoMsgData.Synconfig.AckSynConfig buildPartial() {
        ProtoMsgData.Synconfig.AckSynConfig result = new ProtoMsgData.Synconfig.AckSynConfig(this);
        int from_bitField0_ = bitField0_;
        if (businessconfigBuilder_ == null) {
          if (((bitField0_ & 0x00000001) == 0x00000001)) {
            businessconfig_ = java.util.Collections.unmodifiableList(businessconfig_);
            bitField0_ = (bitField0_ & ~0x00000001);
          }
          result.businessconfig_ = businessconfig_;
        } else {
          result.businessconfig_ = businessconfigBuilder_.build();
        }
        onBuilt();
        return result;
      }
      
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof ProtoMsgData.Synconfig.AckSynConfig) {
          return mergeFrom((ProtoMsgData.Synconfig.AckSynConfig)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }
      
      public Builder mergeFrom(ProtoMsgData.Synconfig.AckSynConfig other) {
        if (other == ProtoMsgData.Synconfig.AckSynConfig.getDefaultInstance()) return this;
        if (businessconfigBuilder_ == null) {
          if (!other.businessconfig_.isEmpty()) {
            if (businessconfig_.isEmpty()) {
              businessconfig_ = other.businessconfig_;
              bitField0_ = (bitField0_ & ~0x00000001);
            } else {
              ensureBusinessconfigIsMutable();
              businessconfig_.addAll(other.businessconfig_);
            }
            onChanged();
          }
        } else {
          if (!other.businessconfig_.isEmpty()) {
            if (businessconfigBuilder_.isEmpty()) {
              businessconfigBuilder_.dispose();
              businessconfigBuilder_ = null;
              businessconfig_ = other.businessconfig_;
              bitField0_ = (bitField0_ & ~0x00000001);
              businessconfigBuilder_ = 
                com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders ?
                   getBusinessconfigFieldBuilder() : null;
            } else {
              businessconfigBuilder_.addAllMessages(other.businessconfig_);
            }
          }
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }
      
      public final boolean isInitialized() {
        for (int i = 0; i < getBusinessconfigCount(); i++) {
          if (!getBusinessconfig(i).isInitialized()) {
            
            return false;
          }
        }
        return true;
      }
      
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder(
            this.getUnknownFields());
        while (true) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              this.setUnknownFields(unknownFields.build());
              onChanged();
              return this;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                this.setUnknownFields(unknownFields.build());
                onChanged();
                return this;
              }
              break;
            }
            case 10: {
              ProtoMsgData.Synconfig.BusinessConfig.Builder subBuilder = ProtoMsgData.Synconfig.BusinessConfig.newBuilder();
              input.readMessage(subBuilder, extensionRegistry);
              addBusinessconfig(subBuilder.buildPartial());
              break;
            }
          }
        }
      }
      
      private int bitField0_;
      
      // repeated .ProtoMsgData.BusinessConfig businessconfig = 1;
      private java.util.List<ProtoMsgData.Synconfig.BusinessConfig> businessconfig_ =
        java.util.Collections.emptyList();
      private void ensureBusinessconfigIsMutable() {
        if (!((bitField0_ & 0x00000001) == 0x00000001)) {
          businessconfig_ = new java.util.ArrayList<ProtoMsgData.Synconfig.BusinessConfig>(businessconfig_);
          bitField0_ |= 0x00000001;
         }
      }
      
      private com.google.protobuf.RepeatedFieldBuilder<
          ProtoMsgData.Synconfig.BusinessConfig, ProtoMsgData.Synconfig.BusinessConfig.Builder, ProtoMsgData.Synconfig.BusinessConfigOrBuilder> businessconfigBuilder_;
      
      public java.util.List<ProtoMsgData.Synconfig.BusinessConfig> getBusinessconfigList() {
        if (businessconfigBuilder_ == null) {
          return java.util.Collections.unmodifiableList(businessconfig_);
        } else {
          return businessconfigBuilder_.getMessageList();
        }
      }
      public int getBusinessconfigCount() {
        if (businessconfigBuilder_ == null) {
          return businessconfig_.size();
        } else {
          return businessconfigBuilder_.getCount();
        }
      }
      public ProtoMsgData.Synconfig.BusinessConfig getBusinessconfig(int index) {
        if (businessconfigBuilder_ == null) {
          return businessconfig_.get(index);
        } else {
          return businessconfigBuilder_.getMessage(index);
        }
      }
      public Builder setBusinessconfig(
          int index, ProtoMsgData.Synconfig.BusinessConfig value) {
        if (businessconfigBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureBusinessconfigIsMutable();
          businessconfig_.set(index, value);
          onChanged();
        } else {
          businessconfigBuilder_.setMessage(index, value);
        }
        return this;
      }
      public Builder setBusinessconfig(
          int index, ProtoMsgData.Synconfig.BusinessConfig.Builder builderForValue) {
        if (businessconfigBuilder_ == null) {
          ensureBusinessconfigIsMutable();
          businessconfig_.set(index, builderForValue.build());
          onChanged();
        } else {
          businessconfigBuilder_.setMessage(index, builderForValue.build());
        }
        return this;
      }
      public Builder addBusinessconfig(ProtoMsgData.Synconfig.BusinessConfig value) {
        if (businessconfigBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureBusinessconfigIsMutable();
          businessconfig_.add(value);
          onChanged();
        } else {
          businessconfigBuilder_.addMessage(value);
        }
        return this;
      }
      public Builder addBusinessconfig(
          int index, ProtoMsgData.Synconfig.BusinessConfig value) {
        if (businessconfigBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureBusinessconfigIsMutable();
          businessconfig_.add(index, value);
          onChanged();
        } else {
          businessconfigBuilder_.addMessage(index, value);
        }
        return this;
      }
      public Builder addBusinessconfig(
          ProtoMsgData.Synconfig.BusinessConfig.Builder builderForValue) {
        if (businessconfigBuilder_ == null) {
          ensureBusinessconfigIsMutable();
          businessconfig_.add(builderForValue.build());
          onChanged();
        } else {
          businessconfigBuilder_.addMessage(builderForValue.build());
        }
        return this;
      }
      public Builder addBusinessconfig(
          int index, ProtoMsgData.Synconfig.BusinessConfig.Builder builderForValue) {
        if (businessconfigBuilder_ == null) {
          ensureBusinessconfigIsMutable();
          businessconfig_.add(index, builderForValue.build());
          onChanged();
        } else {
          businessconfigBuilder_.addMessage(index, builderForValue.build());
        }
        return this;
      }
      public Builder addAllBusinessconfig(
          java.lang.Iterable<? extends ProtoMsgData.Synconfig.BusinessConfig> values) {
        if (businessconfigBuilder_ == null) {
          ensureBusinessconfigIsMutable();
          super.addAll(values, businessconfig_);
          onChanged();
        } else {
          businessconfigBuilder_.addAllMessages(values);
        }
        return this;
      }
      public Builder clearBusinessconfig() {
        if (businessconfigBuilder_ == null) {
          businessconfig_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000001);
          onChanged();
        } else {
          businessconfigBuilder_.clear();
        }
        return this;
      }
      public Builder removeBusinessconfig(int index) {
        if (businessconfigBuilder_ == null) {
          ensureBusinessconfigIsMutable();
          businessconfig_.remove(index);
          onChanged();
        } else {
          businessconfigBuilder_.remove(index);
        }
        return this;
      }
      public ProtoMsgData.Synconfig.BusinessConfig.Builder getBusinessconfigBuilder(
          int index) {
        return getBusinessconfigFieldBuilder().getBuilder(index);
      }
      public ProtoMsgData.Synconfig.BusinessConfigOrBuilder getBusinessconfigOrBuilder(
          int index) {
        if (businessconfigBuilder_ == null) {
          return businessconfig_.get(index);  } else {
          return businessconfigBuilder_.getMessageOrBuilder(index);
        }
      }
      public java.util.List<? extends ProtoMsgData.Synconfig.BusinessConfigOrBuilder> 
           getBusinessconfigOrBuilderList() {
        if (businessconfigBuilder_ != null) {
          return businessconfigBuilder_.getMessageOrBuilderList();
        } else {
          return java.util.Collections.unmodifiableList(businessconfig_);
        }
      }
      public ProtoMsgData.Synconfig.BusinessConfig.Builder addBusinessconfigBuilder() {
        return getBusinessconfigFieldBuilder().addBuilder(
            ProtoMsgData.Synconfig.BusinessConfig.getDefaultInstance());
      }
      public ProtoMsgData.Synconfig.BusinessConfig.Builder addBusinessconfigBuilder(
          int index) {
        return getBusinessconfigFieldBuilder().addBuilder(
            index, ProtoMsgData.Synconfig.BusinessConfig.getDefaultInstance());
      }
      public java.util.List<ProtoMsgData.Synconfig.BusinessConfig.Builder> 
           getBusinessconfigBuilderList() {
        return getBusinessconfigFieldBuilder().getBuilderList();
      }
      private com.google.protobuf.RepeatedFieldBuilder<
          ProtoMsgData.Synconfig.BusinessConfig, ProtoMsgData.Synconfig.BusinessConfig.Builder, ProtoMsgData.Synconfig.BusinessConfigOrBuilder> 
          getBusinessconfigFieldBuilder() {
        if (businessconfigBuilder_ == null) {
          businessconfigBuilder_ = new com.google.protobuf.RepeatedFieldBuilder<
              ProtoMsgData.Synconfig.BusinessConfig, ProtoMsgData.Synconfig.BusinessConfig.Builder, ProtoMsgData.Synconfig.BusinessConfigOrBuilder>(
                  businessconfig_,
                  ((bitField0_ & 0x00000001) == 0x00000001),
                  getParentForChildren(),
                  isClean());
          businessconfig_ = null;
        }
        return businessconfigBuilder_;
      }
      
      // @@protoc_insertion_point(builder_scope:ProtoMsgData.AckSynConfig)
    }
    
    static {
      defaultInstance = new AckSynConfig(true);
      defaultInstance.initFields();
    }
    
    // @@protoc_insertion_point(class_scope:ProtoMsgData.AckSynConfig)
  }
  
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_ProtoMsgData_BusinessConfig_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_ProtoMsgData_BusinessConfig_fieldAccessorTable;
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_ProtoMsgData_AckSynConfig_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_ProtoMsgData_AckSynConfig_fieldAccessorTable;
  
  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\017synconfig.proto\022\014ProtoMsgData\"[\n\016Busin" +
      "essConfig\022\014\n\004type\030\001 \002(\r\022\n\n\002id\030\002 \002(\r\022\r\n\005p" +
      "rice\030\003 \002(\t\022\020\n\010disprice\030\004 \002(\t\022\016\n\006person\030\005" +
      " \002(\t\"D\n\014AckSynConfig\0224\n\016businessconfig\030\001" +
      " \003(\0132\034.ProtoMsgData.BusinessConfig"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
      new com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner() {
        public com.google.protobuf.ExtensionRegistry assignDescriptors(
            com.google.protobuf.Descriptors.FileDescriptor root) {
          descriptor = root;
          internal_static_ProtoMsgData_BusinessConfig_descriptor =
            getDescriptor().getMessageTypes().get(0);
          internal_static_ProtoMsgData_BusinessConfig_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_ProtoMsgData_BusinessConfig_descriptor,
              new java.lang.String[] { "Type", "Id", "Price", "Disprice", "Person", },
              ProtoMsgData.Synconfig.BusinessConfig.class,
              ProtoMsgData.Synconfig.BusinessConfig.Builder.class);
          internal_static_ProtoMsgData_AckSynConfig_descriptor =
            getDescriptor().getMessageTypes().get(1);
          internal_static_ProtoMsgData_AckSynConfig_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_ProtoMsgData_AckSynConfig_descriptor,
              new java.lang.String[] { "Businessconfig", },
              ProtoMsgData.Synconfig.AckSynConfig.class,
              ProtoMsgData.Synconfig.AckSynConfig.Builder.class);
          return null;
        }
      };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
  }
  
  // @@protoc_insertion_point(outer_class_scope)
}
