// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: userinfo.proto

package ProtoMsgData;

public final class Userinfo {
  private Userinfo() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  public interface UserInfoOrBuilder
      extends com.google.protobuf.MessageOrBuilder {
    
    // required uint64 charid = 1;
    boolean hasCharid();
    long getCharid();
    
    // required string account = 2;
    boolean hasAccount();
    String getAccount();
    
    // required uint32 level = 3;
    boolean hasLevel();
    int getLevel();
    
    // required uint32 vouchers = 4;
    boolean hasVouchers();
    int getVouchers();
    
    // required uint32 balance = 5;
    boolean hasBalance();
    int getBalance();
    
    // repeated .ProtoMsgData.AddressInfo addressinfo = 6;
    java.util.List<ProtoMsgData.Business.AddressInfo> 
        getAddressinfoList();
    ProtoMsgData.Business.AddressInfo getAddressinfo(int index);
    int getAddressinfoCount();
    java.util.List<? extends ProtoMsgData.Business.AddressInfoOrBuilder> 
        getAddressinfoOrBuilderList();
    ProtoMsgData.Business.AddressInfoOrBuilder getAddressinfoOrBuilder(
        int index);
    
    // repeated .ProtoMsgData.OrderForm orderform = 7;
    java.util.List<ProtoMsgData.Business.OrderForm> 
        getOrderformList();
    ProtoMsgData.Business.OrderForm getOrderform(int index);
    int getOrderformCount();
    java.util.List<? extends ProtoMsgData.Business.OrderFormOrBuilder> 
        getOrderformOrBuilderList();
    ProtoMsgData.Business.OrderFormOrBuilder getOrderformOrBuilder(
        int index);
    
    // repeated .ProtoMsgData.NoticeInfo notice = 8;
    java.util.List<ProtoMsgData.Notice.NoticeInfo> 
        getNoticeList();
    ProtoMsgData.Notice.NoticeInfo getNotice(int index);
    int getNoticeCount();
    java.util.List<? extends ProtoMsgData.Notice.NoticeInfoOrBuilder> 
        getNoticeOrBuilderList();
    ProtoMsgData.Notice.NoticeInfoOrBuilder getNoticeOrBuilder(
        int index);
  }
  public static final class UserInfo extends
      com.google.protobuf.GeneratedMessage
      implements UserInfoOrBuilder {
    // Use UserInfo.newBuilder() to construct.
    private UserInfo(Builder builder) {
      super(builder);
    }
    private UserInfo(boolean noInit) {}
    
    private static final UserInfo defaultInstance;
    public static UserInfo getDefaultInstance() {
      return defaultInstance;
    }
    
    public UserInfo getDefaultInstanceForType() {
      return defaultInstance;
    }
    
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return ProtoMsgData.Userinfo.internal_static_ProtoMsgData_UserInfo_descriptor;
    }
    
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return ProtoMsgData.Userinfo.internal_static_ProtoMsgData_UserInfo_fieldAccessorTable;
    }
    
    private int bitField0_;
    // required uint64 charid = 1;
    public static final int CHARID_FIELD_NUMBER = 1;
    private long charid_;
    public boolean hasCharid() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    public long getCharid() {
      return charid_;
    }
    
    // required string account = 2;
    public static final int ACCOUNT_FIELD_NUMBER = 2;
    private java.lang.Object account_;
    public boolean hasAccount() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    public String getAccount() {
      java.lang.Object ref = account_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        if (com.google.protobuf.Internal.isValidUtf8(bs)) {
          account_ = s;
        }
        return s;
      }
    }
    private com.google.protobuf.ByteString getAccountBytes() {
      java.lang.Object ref = account_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8((String) ref);
        account_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    
    // required uint32 level = 3;
    public static final int LEVEL_FIELD_NUMBER = 3;
    private int level_;
    public boolean hasLevel() {
      return ((bitField0_ & 0x00000004) == 0x00000004);
    }
    public int getLevel() {
      return level_;
    }
    
    // required uint32 vouchers = 4;
    public static final int VOUCHERS_FIELD_NUMBER = 4;
    private int vouchers_;
    public boolean hasVouchers() {
      return ((bitField0_ & 0x00000008) == 0x00000008);
    }
    public int getVouchers() {
      return vouchers_;
    }
    
    // required uint32 balance = 5;
    public static final int BALANCE_FIELD_NUMBER = 5;
    private int balance_;
    public boolean hasBalance() {
      return ((bitField0_ & 0x00000010) == 0x00000010);
    }
    public int getBalance() {
      return balance_;
    }
    
    // repeated .ProtoMsgData.AddressInfo addressinfo = 6;
    public static final int ADDRESSINFO_FIELD_NUMBER = 6;
    private java.util.List<ProtoMsgData.Business.AddressInfo> addressinfo_;
    public java.util.List<ProtoMsgData.Business.AddressInfo> getAddressinfoList() {
      return addressinfo_;
    }
    public java.util.List<? extends ProtoMsgData.Business.AddressInfoOrBuilder> 
        getAddressinfoOrBuilderList() {
      return addressinfo_;
    }
    public int getAddressinfoCount() {
      return addressinfo_.size();
    }
    public ProtoMsgData.Business.AddressInfo getAddressinfo(int index) {
      return addressinfo_.get(index);
    }
    public ProtoMsgData.Business.AddressInfoOrBuilder getAddressinfoOrBuilder(
        int index) {
      return addressinfo_.get(index);
    }
    
    // repeated .ProtoMsgData.OrderForm orderform = 7;
    public static final int ORDERFORM_FIELD_NUMBER = 7;
    private java.util.List<ProtoMsgData.Business.OrderForm> orderform_;
    public java.util.List<ProtoMsgData.Business.OrderForm> getOrderformList() {
      return orderform_;
    }
    public java.util.List<? extends ProtoMsgData.Business.OrderFormOrBuilder> 
        getOrderformOrBuilderList() {
      return orderform_;
    }
    public int getOrderformCount() {
      return orderform_.size();
    }
    public ProtoMsgData.Business.OrderForm getOrderform(int index) {
      return orderform_.get(index);
    }
    public ProtoMsgData.Business.OrderFormOrBuilder getOrderformOrBuilder(
        int index) {
      return orderform_.get(index);
    }
    
    // repeated .ProtoMsgData.NoticeInfo notice = 8;
    public static final int NOTICE_FIELD_NUMBER = 8;
    private java.util.List<ProtoMsgData.Notice.NoticeInfo> notice_;
    public java.util.List<ProtoMsgData.Notice.NoticeInfo> getNoticeList() {
      return notice_;
    }
    public java.util.List<? extends ProtoMsgData.Notice.NoticeInfoOrBuilder> 
        getNoticeOrBuilderList() {
      return notice_;
    }
    public int getNoticeCount() {
      return notice_.size();
    }
    public ProtoMsgData.Notice.NoticeInfo getNotice(int index) {
      return notice_.get(index);
    }
    public ProtoMsgData.Notice.NoticeInfoOrBuilder getNoticeOrBuilder(
        int index) {
      return notice_.get(index);
    }
    
    private void initFields() {
      charid_ = 0L;
      account_ = "";
      level_ = 0;
      vouchers_ = 0;
      balance_ = 0;
      addressinfo_ = java.util.Collections.emptyList();
      orderform_ = java.util.Collections.emptyList();
      notice_ = java.util.Collections.emptyList();
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;
      
      if (!hasCharid()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasAccount()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasLevel()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasVouchers()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasBalance()) {
        memoizedIsInitialized = 0;
        return false;
      }
      for (int i = 0; i < getAddressinfoCount(); i++) {
        if (!getAddressinfo(i).isInitialized()) {
          memoizedIsInitialized = 0;
          return false;
        }
      }
      for (int i = 0; i < getOrderformCount(); i++) {
        if (!getOrderform(i).isInitialized()) {
          memoizedIsInitialized = 0;
          return false;
        }
      }
      for (int i = 0; i < getNoticeCount(); i++) {
        if (!getNotice(i).isInitialized()) {
          memoizedIsInitialized = 0;
          return false;
        }
      }
      memoizedIsInitialized = 1;
      return true;
    }
    
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeUInt64(1, charid_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeBytes(2, getAccountBytes());
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        output.writeUInt32(3, level_);
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        output.writeUInt32(4, vouchers_);
      }
      if (((bitField0_ & 0x00000010) == 0x00000010)) {
        output.writeUInt32(5, balance_);
      }
      for (int i = 0; i < addressinfo_.size(); i++) {
        output.writeMessage(6, addressinfo_.get(i));
      }
      for (int i = 0; i < orderform_.size(); i++) {
        output.writeMessage(7, orderform_.get(i));
      }
      for (int i = 0; i < notice_.size(); i++) {
        output.writeMessage(8, notice_.get(i));
      }
      getUnknownFields().writeTo(output);
    }
    
    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;
    
      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeUInt64Size(1, charid_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(2, getAccountBytes());
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        size += com.google.protobuf.CodedOutputStream
          .computeUInt32Size(3, level_);
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        size += com.google.protobuf.CodedOutputStream
          .computeUInt32Size(4, vouchers_);
      }
      if (((bitField0_ & 0x00000010) == 0x00000010)) {
        size += com.google.protobuf.CodedOutputStream
          .computeUInt32Size(5, balance_);
      }
      for (int i = 0; i < addressinfo_.size(); i++) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(6, addressinfo_.get(i));
      }
      for (int i = 0; i < orderform_.size(); i++) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(7, orderform_.get(i));
      }
      for (int i = 0; i < notice_.size(); i++) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(8, notice_.get(i));
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }
    
    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }
    
    public static ProtoMsgData.Userinfo.UserInfo parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static ProtoMsgData.Userinfo.UserInfo parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static ProtoMsgData.Userinfo.UserInfo parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static ProtoMsgData.Userinfo.UserInfo parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static ProtoMsgData.Userinfo.UserInfo parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static ProtoMsgData.Userinfo.UserInfo parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    public static ProtoMsgData.Userinfo.UserInfo parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static ProtoMsgData.Userinfo.UserInfo parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input, extensionRegistry)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static ProtoMsgData.Userinfo.UserInfo parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static ProtoMsgData.Userinfo.UserInfo parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    
    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(ProtoMsgData.Userinfo.UserInfo prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }
    
    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements ProtoMsgData.Userinfo.UserInfoOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return ProtoMsgData.Userinfo.internal_static_ProtoMsgData_UserInfo_descriptor;
      }
      
      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return ProtoMsgData.Userinfo.internal_static_ProtoMsgData_UserInfo_fieldAccessorTable;
      }
      
      // Construct using ProtoMsgData.Userinfo.UserInfo.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }
      
      private Builder(BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
          getAddressinfoFieldBuilder();
          getOrderformFieldBuilder();
          getNoticeFieldBuilder();
        }
      }
      private static Builder create() {
        return new Builder();
      }
      
      public Builder clear() {
        super.clear();
        charid_ = 0L;
        bitField0_ = (bitField0_ & ~0x00000001);
        account_ = "";
        bitField0_ = (bitField0_ & ~0x00000002);
        level_ = 0;
        bitField0_ = (bitField0_ & ~0x00000004);
        vouchers_ = 0;
        bitField0_ = (bitField0_ & ~0x00000008);
        balance_ = 0;
        bitField0_ = (bitField0_ & ~0x00000010);
        if (addressinfoBuilder_ == null) {
          addressinfo_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000020);
        } else {
          addressinfoBuilder_.clear();
        }
        if (orderformBuilder_ == null) {
          orderform_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000040);
        } else {
          orderformBuilder_.clear();
        }
        if (noticeBuilder_ == null) {
          notice_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000080);
        } else {
          noticeBuilder_.clear();
        }
        return this;
      }
      
      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }
      
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return ProtoMsgData.Userinfo.UserInfo.getDescriptor();
      }
      
      public ProtoMsgData.Userinfo.UserInfo getDefaultInstanceForType() {
        return ProtoMsgData.Userinfo.UserInfo.getDefaultInstance();
      }
      
      public ProtoMsgData.Userinfo.UserInfo build() {
        ProtoMsgData.Userinfo.UserInfo result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }
      
      private ProtoMsgData.Userinfo.UserInfo buildParsed()
          throws com.google.protobuf.InvalidProtocolBufferException {
        ProtoMsgData.Userinfo.UserInfo result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(
            result).asInvalidProtocolBufferException();
        }
        return result;
      }
      
      public ProtoMsgData.Userinfo.UserInfo buildPartial() {
        ProtoMsgData.Userinfo.UserInfo result = new ProtoMsgData.Userinfo.UserInfo(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.charid_ = charid_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.account_ = account_;
        if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
          to_bitField0_ |= 0x00000004;
        }
        result.level_ = level_;
        if (((from_bitField0_ & 0x00000008) == 0x00000008)) {
          to_bitField0_ |= 0x00000008;
        }
        result.vouchers_ = vouchers_;
        if (((from_bitField0_ & 0x00000010) == 0x00000010)) {
          to_bitField0_ |= 0x00000010;
        }
        result.balance_ = balance_;
        if (addressinfoBuilder_ == null) {
          if (((bitField0_ & 0x00000020) == 0x00000020)) {
            addressinfo_ = java.util.Collections.unmodifiableList(addressinfo_);
            bitField0_ = (bitField0_ & ~0x00000020);
          }
          result.addressinfo_ = addressinfo_;
        } else {
          result.addressinfo_ = addressinfoBuilder_.build();
        }
        if (orderformBuilder_ == null) {
          if (((bitField0_ & 0x00000040) == 0x00000040)) {
            orderform_ = java.util.Collections.unmodifiableList(orderform_);
            bitField0_ = (bitField0_ & ~0x00000040);
          }
          result.orderform_ = orderform_;
        } else {
          result.orderform_ = orderformBuilder_.build();
        }
        if (noticeBuilder_ == null) {
          if (((bitField0_ & 0x00000080) == 0x00000080)) {
            notice_ = java.util.Collections.unmodifiableList(notice_);
            bitField0_ = (bitField0_ & ~0x00000080);
          }
          result.notice_ = notice_;
        } else {
          result.notice_ = noticeBuilder_.build();
        }
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }
      
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof ProtoMsgData.Userinfo.UserInfo) {
          return mergeFrom((ProtoMsgData.Userinfo.UserInfo)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }
      
      public Builder mergeFrom(ProtoMsgData.Userinfo.UserInfo other) {
        if (other == ProtoMsgData.Userinfo.UserInfo.getDefaultInstance()) return this;
        if (other.hasCharid()) {
          setCharid(other.getCharid());
        }
        if (other.hasAccount()) {
          setAccount(other.getAccount());
        }
        if (other.hasLevel()) {
          setLevel(other.getLevel());
        }
        if (other.hasVouchers()) {
          setVouchers(other.getVouchers());
        }
        if (other.hasBalance()) {
          setBalance(other.getBalance());
        }
        if (addressinfoBuilder_ == null) {
          if (!other.addressinfo_.isEmpty()) {
            if (addressinfo_.isEmpty()) {
              addressinfo_ = other.addressinfo_;
              bitField0_ = (bitField0_ & ~0x00000020);
            } else {
              ensureAddressinfoIsMutable();
              addressinfo_.addAll(other.addressinfo_);
            }
            onChanged();
          }
        } else {
          if (!other.addressinfo_.isEmpty()) {
            if (addressinfoBuilder_.isEmpty()) {
              addressinfoBuilder_.dispose();
              addressinfoBuilder_ = null;
              addressinfo_ = other.addressinfo_;
              bitField0_ = (bitField0_ & ~0x00000020);
              addressinfoBuilder_ = 
                com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders ?
                   getAddressinfoFieldBuilder() : null;
            } else {
              addressinfoBuilder_.addAllMessages(other.addressinfo_);
            }
          }
        }
        if (orderformBuilder_ == null) {
          if (!other.orderform_.isEmpty()) {
            if (orderform_.isEmpty()) {
              orderform_ = other.orderform_;
              bitField0_ = (bitField0_ & ~0x00000040);
            } else {
              ensureOrderformIsMutable();
              orderform_.addAll(other.orderform_);
            }
            onChanged();
          }
        } else {
          if (!other.orderform_.isEmpty()) {
            if (orderformBuilder_.isEmpty()) {
              orderformBuilder_.dispose();
              orderformBuilder_ = null;
              orderform_ = other.orderform_;
              bitField0_ = (bitField0_ & ~0x00000040);
              orderformBuilder_ = 
                com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders ?
                   getOrderformFieldBuilder() : null;
            } else {
              orderformBuilder_.addAllMessages(other.orderform_);
            }
          }
        }
        if (noticeBuilder_ == null) {
          if (!other.notice_.isEmpty()) {
            if (notice_.isEmpty()) {
              notice_ = other.notice_;
              bitField0_ = (bitField0_ & ~0x00000080);
            } else {
              ensureNoticeIsMutable();
              notice_.addAll(other.notice_);
            }
            onChanged();
          }
        } else {
          if (!other.notice_.isEmpty()) {
            if (noticeBuilder_.isEmpty()) {
              noticeBuilder_.dispose();
              noticeBuilder_ = null;
              notice_ = other.notice_;
              bitField0_ = (bitField0_ & ~0x00000080);
              noticeBuilder_ = 
                com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders ?
                   getNoticeFieldBuilder() : null;
            } else {
              noticeBuilder_.addAllMessages(other.notice_);
            }
          }
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }
      
      public final boolean isInitialized() {
        if (!hasCharid()) {
          
          return false;
        }
        if (!hasAccount()) {
          
          return false;
        }
        if (!hasLevel()) {
          
          return false;
        }
        if (!hasVouchers()) {
          
          return false;
        }
        if (!hasBalance()) {
          
          return false;
        }
        for (int i = 0; i < getAddressinfoCount(); i++) {
          if (!getAddressinfo(i).isInitialized()) {
            
            return false;
          }
        }
        for (int i = 0; i < getOrderformCount(); i++) {
          if (!getOrderform(i).isInitialized()) {
            
            return false;
          }
        }
        for (int i = 0; i < getNoticeCount(); i++) {
          if (!getNotice(i).isInitialized()) {
            
            return false;
          }
        }
        return true;
      }
      
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder(
            this.getUnknownFields());
        while (true) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              this.setUnknownFields(unknownFields.build());
              onChanged();
              return this;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                this.setUnknownFields(unknownFields.build());
                onChanged();
                return this;
              }
              break;
            }
            case 8: {
              bitField0_ |= 0x00000001;
              charid_ = input.readUInt64();
              break;
            }
            case 18: {
              bitField0_ |= 0x00000002;
              account_ = input.readBytes();
              break;
            }
            case 24: {
              bitField0_ |= 0x00000004;
              level_ = input.readUInt32();
              break;
            }
            case 32: {
              bitField0_ |= 0x00000008;
              vouchers_ = input.readUInt32();
              break;
            }
            case 40: {
              bitField0_ |= 0x00000010;
              balance_ = input.readUInt32();
              break;
            }
            case 50: {
              ProtoMsgData.Business.AddressInfo.Builder subBuilder = ProtoMsgData.Business.AddressInfo.newBuilder();
              input.readMessage(subBuilder, extensionRegistry);
              addAddressinfo(subBuilder.buildPartial());
              break;
            }
            case 58: {
              ProtoMsgData.Business.OrderForm.Builder subBuilder = ProtoMsgData.Business.OrderForm.newBuilder();
              input.readMessage(subBuilder, extensionRegistry);
              addOrderform(subBuilder.buildPartial());
              break;
            }
            case 66: {
              ProtoMsgData.Notice.NoticeInfo.Builder subBuilder = ProtoMsgData.Notice.NoticeInfo.newBuilder();
              input.readMessage(subBuilder, extensionRegistry);
              addNotice(subBuilder.buildPartial());
              break;
            }
          }
        }
      }
      
      private int bitField0_;
      
      // required uint64 charid = 1;
      private long charid_ ;
      public boolean hasCharid() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      public long getCharid() {
        return charid_;
      }
      public Builder setCharid(long value) {
        bitField0_ |= 0x00000001;
        charid_ = value;
        onChanged();
        return this;
      }
      public Builder clearCharid() {
        bitField0_ = (bitField0_ & ~0x00000001);
        charid_ = 0L;
        onChanged();
        return this;
      }
      
      // required string account = 2;
      private java.lang.Object account_ = "";
      public boolean hasAccount() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      public String getAccount() {
        java.lang.Object ref = account_;
        if (!(ref instanceof String)) {
          String s = ((com.google.protobuf.ByteString) ref).toStringUtf8();
          account_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      public Builder setAccount(String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
        account_ = value;
        onChanged();
        return this;
      }
      public Builder clearAccount() {
        bitField0_ = (bitField0_ & ~0x00000002);
        account_ = getDefaultInstance().getAccount();
        onChanged();
        return this;
      }
      void setAccount(com.google.protobuf.ByteString value) {
        bitField0_ |= 0x00000002;
        account_ = value;
        onChanged();
      }
      
      // required uint32 level = 3;
      private int level_ ;
      public boolean hasLevel() {
        return ((bitField0_ & 0x00000004) == 0x00000004);
      }
      public int getLevel() {
        return level_;
      }
      public Builder setLevel(int value) {
        bitField0_ |= 0x00000004;
        level_ = value;
        onChanged();
        return this;
      }
      public Builder clearLevel() {
        bitField0_ = (bitField0_ & ~0x00000004);
        level_ = 0;
        onChanged();
        return this;
      }
      
      // required uint32 vouchers = 4;
      private int vouchers_ ;
      public boolean hasVouchers() {
        return ((bitField0_ & 0x00000008) == 0x00000008);
      }
      public int getVouchers() {
        return vouchers_;
      }
      public Builder setVouchers(int value) {
        bitField0_ |= 0x00000008;
        vouchers_ = value;
        onChanged();
        return this;
      }
      public Builder clearVouchers() {
        bitField0_ = (bitField0_ & ~0x00000008);
        vouchers_ = 0;
        onChanged();
        return this;
      }
      
      // required uint32 balance = 5;
      private int balance_ ;
      public boolean hasBalance() {
        return ((bitField0_ & 0x00000010) == 0x00000010);
      }
      public int getBalance() {
        return balance_;
      }
      public Builder setBalance(int value) {
        bitField0_ |= 0x00000010;
        balance_ = value;
        onChanged();
        return this;
      }
      public Builder clearBalance() {
        bitField0_ = (bitField0_ & ~0x00000010);
        balance_ = 0;
        onChanged();
        return this;
      }
      
      // repeated .ProtoMsgData.AddressInfo addressinfo = 6;
      private java.util.List<ProtoMsgData.Business.AddressInfo> addressinfo_ =
        java.util.Collections.emptyList();
      private void ensureAddressinfoIsMutable() {
        if (!((bitField0_ & 0x00000020) == 0x00000020)) {
          addressinfo_ = new java.util.ArrayList<ProtoMsgData.Business.AddressInfo>(addressinfo_);
          bitField0_ |= 0x00000020;
         }
      }
      
      private com.google.protobuf.RepeatedFieldBuilder<
          ProtoMsgData.Business.AddressInfo, ProtoMsgData.Business.AddressInfo.Builder, ProtoMsgData.Business.AddressInfoOrBuilder> addressinfoBuilder_;
      
      public java.util.List<ProtoMsgData.Business.AddressInfo> getAddressinfoList() {
        if (addressinfoBuilder_ == null) {
          return java.util.Collections.unmodifiableList(addressinfo_);
        } else {
          return addressinfoBuilder_.getMessageList();
        }
      }
      public int getAddressinfoCount() {
        if (addressinfoBuilder_ == null) {
          return addressinfo_.size();
        } else {
          return addressinfoBuilder_.getCount();
        }
      }
      public ProtoMsgData.Business.AddressInfo getAddressinfo(int index) {
        if (addressinfoBuilder_ == null) {
          return addressinfo_.get(index);
        } else {
          return addressinfoBuilder_.getMessage(index);
        }
      }
      public Builder setAddressinfo(
          int index, ProtoMsgData.Business.AddressInfo value) {
        if (addressinfoBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureAddressinfoIsMutable();
          addressinfo_.set(index, value);
          onChanged();
        } else {
          addressinfoBuilder_.setMessage(index, value);
        }
        return this;
      }
      public Builder setAddressinfo(
          int index, ProtoMsgData.Business.AddressInfo.Builder builderForValue) {
        if (addressinfoBuilder_ == null) {
          ensureAddressinfoIsMutable();
          addressinfo_.set(index, builderForValue.build());
          onChanged();
        } else {
          addressinfoBuilder_.setMessage(index, builderForValue.build());
        }
        return this;
      }
      public Builder addAddressinfo(ProtoMsgData.Business.AddressInfo value) {
        if (addressinfoBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureAddressinfoIsMutable();
          addressinfo_.add(value);
          onChanged();
        } else {
          addressinfoBuilder_.addMessage(value);
        }
        return this;
      }
      public Builder addAddressinfo(
          int index, ProtoMsgData.Business.AddressInfo value) {
        if (addressinfoBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureAddressinfoIsMutable();
          addressinfo_.add(index, value);
          onChanged();
        } else {
          addressinfoBuilder_.addMessage(index, value);
        }
        return this;
      }
      public Builder addAddressinfo(
          ProtoMsgData.Business.AddressInfo.Builder builderForValue) {
        if (addressinfoBuilder_ == null) {
          ensureAddressinfoIsMutable();
          addressinfo_.add(builderForValue.build());
          onChanged();
        } else {
          addressinfoBuilder_.addMessage(builderForValue.build());
        }
        return this;
      }
      public Builder addAddressinfo(
          int index, ProtoMsgData.Business.AddressInfo.Builder builderForValue) {
        if (addressinfoBuilder_ == null) {
          ensureAddressinfoIsMutable();
          addressinfo_.add(index, builderForValue.build());
          onChanged();
        } else {
          addressinfoBuilder_.addMessage(index, builderForValue.build());
        }
        return this;
      }
      public Builder addAllAddressinfo(
          java.lang.Iterable<? extends ProtoMsgData.Business.AddressInfo> values) {
        if (addressinfoBuilder_ == null) {
          ensureAddressinfoIsMutable();
          super.addAll(values, addressinfo_);
          onChanged();
        } else {
          addressinfoBuilder_.addAllMessages(values);
        }
        return this;
      }
      public Builder clearAddressinfo() {
        if (addressinfoBuilder_ == null) {
          addressinfo_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000020);
          onChanged();
        } else {
          addressinfoBuilder_.clear();
        }
        return this;
      }
      public Builder removeAddressinfo(int index) {
        if (addressinfoBuilder_ == null) {
          ensureAddressinfoIsMutable();
          addressinfo_.remove(index);
          onChanged();
        } else {
          addressinfoBuilder_.remove(index);
        }
        return this;
      }
      public ProtoMsgData.Business.AddressInfo.Builder getAddressinfoBuilder(
          int index) {
        return getAddressinfoFieldBuilder().getBuilder(index);
      }
      public ProtoMsgData.Business.AddressInfoOrBuilder getAddressinfoOrBuilder(
          int index) {
        if (addressinfoBuilder_ == null) {
          return addressinfo_.get(index);  } else {
          return addressinfoBuilder_.getMessageOrBuilder(index);
        }
      }
      public java.util.List<? extends ProtoMsgData.Business.AddressInfoOrBuilder> 
           getAddressinfoOrBuilderList() {
        if (addressinfoBuilder_ != null) {
          return addressinfoBuilder_.getMessageOrBuilderList();
        } else {
          return java.util.Collections.unmodifiableList(addressinfo_);
        }
      }
      public ProtoMsgData.Business.AddressInfo.Builder addAddressinfoBuilder() {
        return getAddressinfoFieldBuilder().addBuilder(
            ProtoMsgData.Business.AddressInfo.getDefaultInstance());
      }
      public ProtoMsgData.Business.AddressInfo.Builder addAddressinfoBuilder(
          int index) {
        return getAddressinfoFieldBuilder().addBuilder(
            index, ProtoMsgData.Business.AddressInfo.getDefaultInstance());
      }
      public java.util.List<ProtoMsgData.Business.AddressInfo.Builder> 
           getAddressinfoBuilderList() {
        return getAddressinfoFieldBuilder().getBuilderList();
      }
      private com.google.protobuf.RepeatedFieldBuilder<
          ProtoMsgData.Business.AddressInfo, ProtoMsgData.Business.AddressInfo.Builder, ProtoMsgData.Business.AddressInfoOrBuilder> 
          getAddressinfoFieldBuilder() {
        if (addressinfoBuilder_ == null) {
          addressinfoBuilder_ = new com.google.protobuf.RepeatedFieldBuilder<
              ProtoMsgData.Business.AddressInfo, ProtoMsgData.Business.AddressInfo.Builder, ProtoMsgData.Business.AddressInfoOrBuilder>(
                  addressinfo_,
                  ((bitField0_ & 0x00000020) == 0x00000020),
                  getParentForChildren(),
                  isClean());
          addressinfo_ = null;
        }
        return addressinfoBuilder_;
      }
      
      // repeated .ProtoMsgData.OrderForm orderform = 7;
      private java.util.List<ProtoMsgData.Business.OrderForm> orderform_ =
        java.util.Collections.emptyList();
      private void ensureOrderformIsMutable() {
        if (!((bitField0_ & 0x00000040) == 0x00000040)) {
          orderform_ = new java.util.ArrayList<ProtoMsgData.Business.OrderForm>(orderform_);
          bitField0_ |= 0x00000040;
         }
      }
      
      private com.google.protobuf.RepeatedFieldBuilder<
          ProtoMsgData.Business.OrderForm, ProtoMsgData.Business.OrderForm.Builder, ProtoMsgData.Business.OrderFormOrBuilder> orderformBuilder_;
      
      public java.util.List<ProtoMsgData.Business.OrderForm> getOrderformList() {
        if (orderformBuilder_ == null) {
          return java.util.Collections.unmodifiableList(orderform_);
        } else {
          return orderformBuilder_.getMessageList();
        }
      }
      public int getOrderformCount() {
        if (orderformBuilder_ == null) {
          return orderform_.size();
        } else {
          return orderformBuilder_.getCount();
        }
      }
      public ProtoMsgData.Business.OrderForm getOrderform(int index) {
        if (orderformBuilder_ == null) {
          return orderform_.get(index);
        } else {
          return orderformBuilder_.getMessage(index);
        }
      }
      public Builder setOrderform(
          int index, ProtoMsgData.Business.OrderForm value) {
        if (orderformBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureOrderformIsMutable();
          orderform_.set(index, value);
          onChanged();
        } else {
          orderformBuilder_.setMessage(index, value);
        }
        return this;
      }
      public Builder setOrderform(
          int index, ProtoMsgData.Business.OrderForm.Builder builderForValue) {
        if (orderformBuilder_ == null) {
          ensureOrderformIsMutable();
          orderform_.set(index, builderForValue.build());
          onChanged();
        } else {
          orderformBuilder_.setMessage(index, builderForValue.build());
        }
        return this;
      }
      public Builder addOrderform(ProtoMsgData.Business.OrderForm value) {
        if (orderformBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureOrderformIsMutable();
          orderform_.add(value);
          onChanged();
        } else {
          orderformBuilder_.addMessage(value);
        }
        return this;
      }
      public Builder addOrderform(
          int index, ProtoMsgData.Business.OrderForm value) {
        if (orderformBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureOrderformIsMutable();
          orderform_.add(index, value);
          onChanged();
        } else {
          orderformBuilder_.addMessage(index, value);
        }
        return this;
      }
      public Builder addOrderform(
          ProtoMsgData.Business.OrderForm.Builder builderForValue) {
        if (orderformBuilder_ == null) {
          ensureOrderformIsMutable();
          orderform_.add(builderForValue.build());
          onChanged();
        } else {
          orderformBuilder_.addMessage(builderForValue.build());
        }
        return this;
      }
      public Builder addOrderform(
          int index, ProtoMsgData.Business.OrderForm.Builder builderForValue) {
        if (orderformBuilder_ == null) {
          ensureOrderformIsMutable();
          orderform_.add(index, builderForValue.build());
          onChanged();
        } else {
          orderformBuilder_.addMessage(index, builderForValue.build());
        }
        return this;
      }
      public Builder addAllOrderform(
          java.lang.Iterable<? extends ProtoMsgData.Business.OrderForm> values) {
        if (orderformBuilder_ == null) {
          ensureOrderformIsMutable();
          super.addAll(values, orderform_);
          onChanged();
        } else {
          orderformBuilder_.addAllMessages(values);
        }
        return this;
      }
      public Builder clearOrderform() {
        if (orderformBuilder_ == null) {
          orderform_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000040);
          onChanged();
        } else {
          orderformBuilder_.clear();
        }
        return this;
      }
      public Builder removeOrderform(int index) {
        if (orderformBuilder_ == null) {
          ensureOrderformIsMutable();
          orderform_.remove(index);
          onChanged();
        } else {
          orderformBuilder_.remove(index);
        }
        return this;
      }
      public ProtoMsgData.Business.OrderForm.Builder getOrderformBuilder(
          int index) {
        return getOrderformFieldBuilder().getBuilder(index);
      }
      public ProtoMsgData.Business.OrderFormOrBuilder getOrderformOrBuilder(
          int index) {
        if (orderformBuilder_ == null) {
          return orderform_.get(index);  } else {
          return orderformBuilder_.getMessageOrBuilder(index);
        }
      }
      public java.util.List<? extends ProtoMsgData.Business.OrderFormOrBuilder> 
           getOrderformOrBuilderList() {
        if (orderformBuilder_ != null) {
          return orderformBuilder_.getMessageOrBuilderList();
        } else {
          return java.util.Collections.unmodifiableList(orderform_);
        }
      }
      public ProtoMsgData.Business.OrderForm.Builder addOrderformBuilder() {
        return getOrderformFieldBuilder().addBuilder(
            ProtoMsgData.Business.OrderForm.getDefaultInstance());
      }
      public ProtoMsgData.Business.OrderForm.Builder addOrderformBuilder(
          int index) {
        return getOrderformFieldBuilder().addBuilder(
            index, ProtoMsgData.Business.OrderForm.getDefaultInstance());
      }
      public java.util.List<ProtoMsgData.Business.OrderForm.Builder> 
           getOrderformBuilderList() {
        return getOrderformFieldBuilder().getBuilderList();
      }
      private com.google.protobuf.RepeatedFieldBuilder<
          ProtoMsgData.Business.OrderForm, ProtoMsgData.Business.OrderForm.Builder, ProtoMsgData.Business.OrderFormOrBuilder> 
          getOrderformFieldBuilder() {
        if (orderformBuilder_ == null) {
          orderformBuilder_ = new com.google.protobuf.RepeatedFieldBuilder<
              ProtoMsgData.Business.OrderForm, ProtoMsgData.Business.OrderForm.Builder, ProtoMsgData.Business.OrderFormOrBuilder>(
                  orderform_,
                  ((bitField0_ & 0x00000040) == 0x00000040),
                  getParentForChildren(),
                  isClean());
          orderform_ = null;
        }
        return orderformBuilder_;
      }
      
      // repeated .ProtoMsgData.NoticeInfo notice = 8;
      private java.util.List<ProtoMsgData.Notice.NoticeInfo> notice_ =
        java.util.Collections.emptyList();
      private void ensureNoticeIsMutable() {
        if (!((bitField0_ & 0x00000080) == 0x00000080)) {
          notice_ = new java.util.ArrayList<ProtoMsgData.Notice.NoticeInfo>(notice_);
          bitField0_ |= 0x00000080;
         }
      }
      
      private com.google.protobuf.RepeatedFieldBuilder<
          ProtoMsgData.Notice.NoticeInfo, ProtoMsgData.Notice.NoticeInfo.Builder, ProtoMsgData.Notice.NoticeInfoOrBuilder> noticeBuilder_;
      
      public java.util.List<ProtoMsgData.Notice.NoticeInfo> getNoticeList() {
        if (noticeBuilder_ == null) {
          return java.util.Collections.unmodifiableList(notice_);
        } else {
          return noticeBuilder_.getMessageList();
        }
      }
      public int getNoticeCount() {
        if (noticeBuilder_ == null) {
          return notice_.size();
        } else {
          return noticeBuilder_.getCount();
        }
      }
      public ProtoMsgData.Notice.NoticeInfo getNotice(int index) {
        if (noticeBuilder_ == null) {
          return notice_.get(index);
        } else {
          return noticeBuilder_.getMessage(index);
        }
      }
      public Builder setNotice(
          int index, ProtoMsgData.Notice.NoticeInfo value) {
        if (noticeBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureNoticeIsMutable();
          notice_.set(index, value);
          onChanged();
        } else {
          noticeBuilder_.setMessage(index, value);
        }
        return this;
      }
      public Builder setNotice(
          int index, ProtoMsgData.Notice.NoticeInfo.Builder builderForValue) {
        if (noticeBuilder_ == null) {
          ensureNoticeIsMutable();
          notice_.set(index, builderForValue.build());
          onChanged();
        } else {
          noticeBuilder_.setMessage(index, builderForValue.build());
        }
        return this;
      }
      public Builder addNotice(ProtoMsgData.Notice.NoticeInfo value) {
        if (noticeBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureNoticeIsMutable();
          notice_.add(value);
          onChanged();
        } else {
          noticeBuilder_.addMessage(value);
        }
        return this;
      }
      public Builder addNotice(
          int index, ProtoMsgData.Notice.NoticeInfo value) {
        if (noticeBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureNoticeIsMutable();
          notice_.add(index, value);
          onChanged();
        } else {
          noticeBuilder_.addMessage(index, value);
        }
        return this;
      }
      public Builder addNotice(
          ProtoMsgData.Notice.NoticeInfo.Builder builderForValue) {
        if (noticeBuilder_ == null) {
          ensureNoticeIsMutable();
          notice_.add(builderForValue.build());
          onChanged();
        } else {
          noticeBuilder_.addMessage(builderForValue.build());
        }
        return this;
      }
      public Builder addNotice(
          int index, ProtoMsgData.Notice.NoticeInfo.Builder builderForValue) {
        if (noticeBuilder_ == null) {
          ensureNoticeIsMutable();
          notice_.add(index, builderForValue.build());
          onChanged();
        } else {
          noticeBuilder_.addMessage(index, builderForValue.build());
        }
        return this;
      }
      public Builder addAllNotice(
          java.lang.Iterable<? extends ProtoMsgData.Notice.NoticeInfo> values) {
        if (noticeBuilder_ == null) {
          ensureNoticeIsMutable();
          super.addAll(values, notice_);
          onChanged();
        } else {
          noticeBuilder_.addAllMessages(values);
        }
        return this;
      }
      public Builder clearNotice() {
        if (noticeBuilder_ == null) {
          notice_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000080);
          onChanged();
        } else {
          noticeBuilder_.clear();
        }
        return this;
      }
      public Builder removeNotice(int index) {
        if (noticeBuilder_ == null) {
          ensureNoticeIsMutable();
          notice_.remove(index);
          onChanged();
        } else {
          noticeBuilder_.remove(index);
        }
        return this;
      }
      public ProtoMsgData.Notice.NoticeInfo.Builder getNoticeBuilder(
          int index) {
        return getNoticeFieldBuilder().getBuilder(index);
      }
      public ProtoMsgData.Notice.NoticeInfoOrBuilder getNoticeOrBuilder(
          int index) {
        if (noticeBuilder_ == null) {
          return notice_.get(index);  } else {
          return noticeBuilder_.getMessageOrBuilder(index);
        }
      }
      public java.util.List<? extends ProtoMsgData.Notice.NoticeInfoOrBuilder> 
           getNoticeOrBuilderList() {
        if (noticeBuilder_ != null) {
          return noticeBuilder_.getMessageOrBuilderList();
        } else {
          return java.util.Collections.unmodifiableList(notice_);
        }
      }
      public ProtoMsgData.Notice.NoticeInfo.Builder addNoticeBuilder() {
        return getNoticeFieldBuilder().addBuilder(
            ProtoMsgData.Notice.NoticeInfo.getDefaultInstance());
      }
      public ProtoMsgData.Notice.NoticeInfo.Builder addNoticeBuilder(
          int index) {
        return getNoticeFieldBuilder().addBuilder(
            index, ProtoMsgData.Notice.NoticeInfo.getDefaultInstance());
      }
      public java.util.List<ProtoMsgData.Notice.NoticeInfo.Builder> 
           getNoticeBuilderList() {
        return getNoticeFieldBuilder().getBuilderList();
      }
      private com.google.protobuf.RepeatedFieldBuilder<
          ProtoMsgData.Notice.NoticeInfo, ProtoMsgData.Notice.NoticeInfo.Builder, ProtoMsgData.Notice.NoticeInfoOrBuilder> 
          getNoticeFieldBuilder() {
        if (noticeBuilder_ == null) {
          noticeBuilder_ = new com.google.protobuf.RepeatedFieldBuilder<
              ProtoMsgData.Notice.NoticeInfo, ProtoMsgData.Notice.NoticeInfo.Builder, ProtoMsgData.Notice.NoticeInfoOrBuilder>(
                  notice_,
                  ((bitField0_ & 0x00000080) == 0x00000080),
                  getParentForChildren(),
                  isClean());
          notice_ = null;
        }
        return noticeBuilder_;
      }
      
      // @@protoc_insertion_point(builder_scope:ProtoMsgData.UserInfo)
    }
    
    static {
      defaultInstance = new UserInfo(true);
      defaultInstance.initFields();
    }
    
    // @@protoc_insertion_point(class_scope:ProtoMsgData.UserInfo)
  }
  
  public interface ReqCreateRoleOrBuilder
      extends com.google.protobuf.MessageOrBuilder {
  }
  public static final class ReqCreateRole extends
      com.google.protobuf.GeneratedMessage
      implements ReqCreateRoleOrBuilder {
    // Use ReqCreateRole.newBuilder() to construct.
    private ReqCreateRole(Builder builder) {
      super(builder);
    }
    private ReqCreateRole(boolean noInit) {}
    
    private static final ReqCreateRole defaultInstance;
    public static ReqCreateRole getDefaultInstance() {
      return defaultInstance;
    }
    
    public ReqCreateRole getDefaultInstanceForType() {
      return defaultInstance;
    }
    
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return ProtoMsgData.Userinfo.internal_static_ProtoMsgData_ReqCreateRole_descriptor;
    }
    
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return ProtoMsgData.Userinfo.internal_static_ProtoMsgData_ReqCreateRole_fieldAccessorTable;
    }
    
    private void initFields() {
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;
      
      memoizedIsInitialized = 1;
      return true;
    }
    
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      getUnknownFields().writeTo(output);
    }
    
    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;
    
      size = 0;
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }
    
    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }
    
    public static ProtoMsgData.Userinfo.ReqCreateRole parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static ProtoMsgData.Userinfo.ReqCreateRole parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static ProtoMsgData.Userinfo.ReqCreateRole parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static ProtoMsgData.Userinfo.ReqCreateRole parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static ProtoMsgData.Userinfo.ReqCreateRole parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static ProtoMsgData.Userinfo.ReqCreateRole parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    public static ProtoMsgData.Userinfo.ReqCreateRole parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static ProtoMsgData.Userinfo.ReqCreateRole parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input, extensionRegistry)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static ProtoMsgData.Userinfo.ReqCreateRole parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static ProtoMsgData.Userinfo.ReqCreateRole parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    
    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(ProtoMsgData.Userinfo.ReqCreateRole prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }
    
    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements ProtoMsgData.Userinfo.ReqCreateRoleOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return ProtoMsgData.Userinfo.internal_static_ProtoMsgData_ReqCreateRole_descriptor;
      }
      
      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return ProtoMsgData.Userinfo.internal_static_ProtoMsgData_ReqCreateRole_fieldAccessorTable;
      }
      
      // Construct using ProtoMsgData.Userinfo.ReqCreateRole.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }
      
      private Builder(BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }
      
      public Builder clear() {
        super.clear();
        return this;
      }
      
      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }
      
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return ProtoMsgData.Userinfo.ReqCreateRole.getDescriptor();
      }
      
      public ProtoMsgData.Userinfo.ReqCreateRole getDefaultInstanceForType() {
        return ProtoMsgData.Userinfo.ReqCreateRole.getDefaultInstance();
      }
      
      public ProtoMsgData.Userinfo.ReqCreateRole build() {
        ProtoMsgData.Userinfo.ReqCreateRole result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }
      
      private ProtoMsgData.Userinfo.ReqCreateRole buildParsed()
          throws com.google.protobuf.InvalidProtocolBufferException {
        ProtoMsgData.Userinfo.ReqCreateRole result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(
            result).asInvalidProtocolBufferException();
        }
        return result;
      }
      
      public ProtoMsgData.Userinfo.ReqCreateRole buildPartial() {
        ProtoMsgData.Userinfo.ReqCreateRole result = new ProtoMsgData.Userinfo.ReqCreateRole(this);
        onBuilt();
        return result;
      }
      
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof ProtoMsgData.Userinfo.ReqCreateRole) {
          return mergeFrom((ProtoMsgData.Userinfo.ReqCreateRole)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }
      
      public Builder mergeFrom(ProtoMsgData.Userinfo.ReqCreateRole other) {
        if (other == ProtoMsgData.Userinfo.ReqCreateRole.getDefaultInstance()) return this;
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }
      
      public final boolean isInitialized() {
        return true;
      }
      
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder(
            this.getUnknownFields());
        while (true) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              this.setUnknownFields(unknownFields.build());
              onChanged();
              return this;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                this.setUnknownFields(unknownFields.build());
                onChanged();
                return this;
              }
              break;
            }
          }
        }
      }
      
      
      // @@protoc_insertion_point(builder_scope:ProtoMsgData.ReqCreateRole)
    }
    
    static {
      defaultInstance = new ReqCreateRole(true);
      defaultInstance.initFields();
    }
    
    // @@protoc_insertion_point(class_scope:ProtoMsgData.ReqCreateRole)
  }
  
  public interface AckUserInfoOrBuilder
      extends com.google.protobuf.MessageOrBuilder {
    
    // required .ProtoMsgData.UserInfo userinfo = 1;
    boolean hasUserinfo();
    ProtoMsgData.Userinfo.UserInfo getUserinfo();
    ProtoMsgData.Userinfo.UserInfoOrBuilder getUserinfoOrBuilder();
  }
  public static final class AckUserInfo extends
      com.google.protobuf.GeneratedMessage
      implements AckUserInfoOrBuilder {
    // Use AckUserInfo.newBuilder() to construct.
    private AckUserInfo(Builder builder) {
      super(builder);
    }
    private AckUserInfo(boolean noInit) {}
    
    private static final AckUserInfo defaultInstance;
    public static AckUserInfo getDefaultInstance() {
      return defaultInstance;
    }
    
    public AckUserInfo getDefaultInstanceForType() {
      return defaultInstance;
    }
    
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return ProtoMsgData.Userinfo.internal_static_ProtoMsgData_AckUserInfo_descriptor;
    }
    
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return ProtoMsgData.Userinfo.internal_static_ProtoMsgData_AckUserInfo_fieldAccessorTable;
    }
    
    private int bitField0_;
    // required .ProtoMsgData.UserInfo userinfo = 1;
    public static final int USERINFO_FIELD_NUMBER = 1;
    private ProtoMsgData.Userinfo.UserInfo userinfo_;
    public boolean hasUserinfo() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    public ProtoMsgData.Userinfo.UserInfo getUserinfo() {
      return userinfo_;
    }
    public ProtoMsgData.Userinfo.UserInfoOrBuilder getUserinfoOrBuilder() {
      return userinfo_;
    }
    
    private void initFields() {
      userinfo_ = ProtoMsgData.Userinfo.UserInfo.getDefaultInstance();
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;
      
      if (!hasUserinfo()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!getUserinfo().isInitialized()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }
    
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeMessage(1, userinfo_);
      }
      getUnknownFields().writeTo(output);
    }
    
    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;
    
      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(1, userinfo_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }
    
    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }
    
    public static ProtoMsgData.Userinfo.AckUserInfo parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static ProtoMsgData.Userinfo.AckUserInfo parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static ProtoMsgData.Userinfo.AckUserInfo parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static ProtoMsgData.Userinfo.AckUserInfo parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static ProtoMsgData.Userinfo.AckUserInfo parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static ProtoMsgData.Userinfo.AckUserInfo parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    public static ProtoMsgData.Userinfo.AckUserInfo parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static ProtoMsgData.Userinfo.AckUserInfo parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input, extensionRegistry)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static ProtoMsgData.Userinfo.AckUserInfo parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static ProtoMsgData.Userinfo.AckUserInfo parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    
    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(ProtoMsgData.Userinfo.AckUserInfo prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }
    
    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements ProtoMsgData.Userinfo.AckUserInfoOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return ProtoMsgData.Userinfo.internal_static_ProtoMsgData_AckUserInfo_descriptor;
      }
      
      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return ProtoMsgData.Userinfo.internal_static_ProtoMsgData_AckUserInfo_fieldAccessorTable;
      }
      
      // Construct using ProtoMsgData.Userinfo.AckUserInfo.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }
      
      private Builder(BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
          getUserinfoFieldBuilder();
        }
      }
      private static Builder create() {
        return new Builder();
      }
      
      public Builder clear() {
        super.clear();
        if (userinfoBuilder_ == null) {
          userinfo_ = ProtoMsgData.Userinfo.UserInfo.getDefaultInstance();
        } else {
          userinfoBuilder_.clear();
        }
        bitField0_ = (bitField0_ & ~0x00000001);
        return this;
      }
      
      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }
      
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return ProtoMsgData.Userinfo.AckUserInfo.getDescriptor();
      }
      
      public ProtoMsgData.Userinfo.AckUserInfo getDefaultInstanceForType() {
        return ProtoMsgData.Userinfo.AckUserInfo.getDefaultInstance();
      }
      
      public ProtoMsgData.Userinfo.AckUserInfo build() {
        ProtoMsgData.Userinfo.AckUserInfo result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }
      
      private ProtoMsgData.Userinfo.AckUserInfo buildParsed()
          throws com.google.protobuf.InvalidProtocolBufferException {
        ProtoMsgData.Userinfo.AckUserInfo result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(
            result).asInvalidProtocolBufferException();
        }
        return result;
      }
      
      public ProtoMsgData.Userinfo.AckUserInfo buildPartial() {
        ProtoMsgData.Userinfo.AckUserInfo result = new ProtoMsgData.Userinfo.AckUserInfo(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        if (userinfoBuilder_ == null) {
          result.userinfo_ = userinfo_;
        } else {
          result.userinfo_ = userinfoBuilder_.build();
        }
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }
      
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof ProtoMsgData.Userinfo.AckUserInfo) {
          return mergeFrom((ProtoMsgData.Userinfo.AckUserInfo)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }
      
      public Builder mergeFrom(ProtoMsgData.Userinfo.AckUserInfo other) {
        if (other == ProtoMsgData.Userinfo.AckUserInfo.getDefaultInstance()) return this;
        if (other.hasUserinfo()) {
          mergeUserinfo(other.getUserinfo());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }
      
      public final boolean isInitialized() {
        if (!hasUserinfo()) {
          
          return false;
        }
        if (!getUserinfo().isInitialized()) {
          
          return false;
        }
        return true;
      }
      
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder(
            this.getUnknownFields());
        while (true) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              this.setUnknownFields(unknownFields.build());
              onChanged();
              return this;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                this.setUnknownFields(unknownFields.build());
                onChanged();
                return this;
              }
              break;
            }
            case 10: {
              ProtoMsgData.Userinfo.UserInfo.Builder subBuilder = ProtoMsgData.Userinfo.UserInfo.newBuilder();
              if (hasUserinfo()) {
                subBuilder.mergeFrom(getUserinfo());
              }
              input.readMessage(subBuilder, extensionRegistry);
              setUserinfo(subBuilder.buildPartial());
              break;
            }
          }
        }
      }
      
      private int bitField0_;
      
      // required .ProtoMsgData.UserInfo userinfo = 1;
      private ProtoMsgData.Userinfo.UserInfo userinfo_ = ProtoMsgData.Userinfo.UserInfo.getDefaultInstance();
      private com.google.protobuf.SingleFieldBuilder<
          ProtoMsgData.Userinfo.UserInfo, ProtoMsgData.Userinfo.UserInfo.Builder, ProtoMsgData.Userinfo.UserInfoOrBuilder> userinfoBuilder_;
      public boolean hasUserinfo() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      public ProtoMsgData.Userinfo.UserInfo getUserinfo() {
        if (userinfoBuilder_ == null) {
          return userinfo_;
        } else {
          return userinfoBuilder_.getMessage();
        }
      }
      public Builder setUserinfo(ProtoMsgData.Userinfo.UserInfo value) {
        if (userinfoBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          userinfo_ = value;
          onChanged();
        } else {
          userinfoBuilder_.setMessage(value);
        }
        bitField0_ |= 0x00000001;
        return this;
      }
      public Builder setUserinfo(
          ProtoMsgData.Userinfo.UserInfo.Builder builderForValue) {
        if (userinfoBuilder_ == null) {
          userinfo_ = builderForValue.build();
          onChanged();
        } else {
          userinfoBuilder_.setMessage(builderForValue.build());
        }
        bitField0_ |= 0x00000001;
        return this;
      }
      public Builder mergeUserinfo(ProtoMsgData.Userinfo.UserInfo value) {
        if (userinfoBuilder_ == null) {
          if (((bitField0_ & 0x00000001) == 0x00000001) &&
              userinfo_ != ProtoMsgData.Userinfo.UserInfo.getDefaultInstance()) {
            userinfo_ =
              ProtoMsgData.Userinfo.UserInfo.newBuilder(userinfo_).mergeFrom(value).buildPartial();
          } else {
            userinfo_ = value;
          }
          onChanged();
        } else {
          userinfoBuilder_.mergeFrom(value);
        }
        bitField0_ |= 0x00000001;
        return this;
      }
      public Builder clearUserinfo() {
        if (userinfoBuilder_ == null) {
          userinfo_ = ProtoMsgData.Userinfo.UserInfo.getDefaultInstance();
          onChanged();
        } else {
          userinfoBuilder_.clear();
        }
        bitField0_ = (bitField0_ & ~0x00000001);
        return this;
      }
      public ProtoMsgData.Userinfo.UserInfo.Builder getUserinfoBuilder() {
        bitField0_ |= 0x00000001;
        onChanged();
        return getUserinfoFieldBuilder().getBuilder();
      }
      public ProtoMsgData.Userinfo.UserInfoOrBuilder getUserinfoOrBuilder() {
        if (userinfoBuilder_ != null) {
          return userinfoBuilder_.getMessageOrBuilder();
        } else {
          return userinfo_;
        }
      }
      private com.google.protobuf.SingleFieldBuilder<
          ProtoMsgData.Userinfo.UserInfo, ProtoMsgData.Userinfo.UserInfo.Builder, ProtoMsgData.Userinfo.UserInfoOrBuilder> 
          getUserinfoFieldBuilder() {
        if (userinfoBuilder_ == null) {
          userinfoBuilder_ = new com.google.protobuf.SingleFieldBuilder<
              ProtoMsgData.Userinfo.UserInfo, ProtoMsgData.Userinfo.UserInfo.Builder, ProtoMsgData.Userinfo.UserInfoOrBuilder>(
                  userinfo_,
                  getParentForChildren(),
                  isClean());
          userinfo_ = null;
        }
        return userinfoBuilder_;
      }
      
      // @@protoc_insertion_point(builder_scope:ProtoMsgData.AckUserInfo)
    }
    
    static {
      defaultInstance = new AckUserInfo(true);
      defaultInstance.initFields();
    }
    
    // @@protoc_insertion_point(class_scope:ProtoMsgData.AckUserInfo)
  }
  
  public interface AckSystemTimeOrBuilder
      extends com.google.protobuf.MessageOrBuilder {
    
    // required uint64 time = 1;
    boolean hasTime();
    long getTime();
  }
  public static final class AckSystemTime extends
      com.google.protobuf.GeneratedMessage
      implements AckSystemTimeOrBuilder {
    // Use AckSystemTime.newBuilder() to construct.
    private AckSystemTime(Builder builder) {
      super(builder);
    }
    private AckSystemTime(boolean noInit) {}
    
    private static final AckSystemTime defaultInstance;
    public static AckSystemTime getDefaultInstance() {
      return defaultInstance;
    }
    
    public AckSystemTime getDefaultInstanceForType() {
      return defaultInstance;
    }
    
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return ProtoMsgData.Userinfo.internal_static_ProtoMsgData_AckSystemTime_descriptor;
    }
    
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return ProtoMsgData.Userinfo.internal_static_ProtoMsgData_AckSystemTime_fieldAccessorTable;
    }
    
    private int bitField0_;
    // required uint64 time = 1;
    public static final int TIME_FIELD_NUMBER = 1;
    private long time_;
    public boolean hasTime() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    public long getTime() {
      return time_;
    }
    
    private void initFields() {
      time_ = 0L;
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;
      
      if (!hasTime()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }
    
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeUInt64(1, time_);
      }
      getUnknownFields().writeTo(output);
    }
    
    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;
    
      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeUInt64Size(1, time_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }
    
    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }
    
    public static ProtoMsgData.Userinfo.AckSystemTime parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static ProtoMsgData.Userinfo.AckSystemTime parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static ProtoMsgData.Userinfo.AckSystemTime parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static ProtoMsgData.Userinfo.AckSystemTime parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static ProtoMsgData.Userinfo.AckSystemTime parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static ProtoMsgData.Userinfo.AckSystemTime parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    public static ProtoMsgData.Userinfo.AckSystemTime parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static ProtoMsgData.Userinfo.AckSystemTime parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input, extensionRegistry)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static ProtoMsgData.Userinfo.AckSystemTime parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static ProtoMsgData.Userinfo.AckSystemTime parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    
    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(ProtoMsgData.Userinfo.AckSystemTime prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }
    
    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements ProtoMsgData.Userinfo.AckSystemTimeOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return ProtoMsgData.Userinfo.internal_static_ProtoMsgData_AckSystemTime_descriptor;
      }
      
      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return ProtoMsgData.Userinfo.internal_static_ProtoMsgData_AckSystemTime_fieldAccessorTable;
      }
      
      // Construct using ProtoMsgData.Userinfo.AckSystemTime.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }
      
      private Builder(BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }
      
      public Builder clear() {
        super.clear();
        time_ = 0L;
        bitField0_ = (bitField0_ & ~0x00000001);
        return this;
      }
      
      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }
      
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return ProtoMsgData.Userinfo.AckSystemTime.getDescriptor();
      }
      
      public ProtoMsgData.Userinfo.AckSystemTime getDefaultInstanceForType() {
        return ProtoMsgData.Userinfo.AckSystemTime.getDefaultInstance();
      }
      
      public ProtoMsgData.Userinfo.AckSystemTime build() {
        ProtoMsgData.Userinfo.AckSystemTime result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }
      
      private ProtoMsgData.Userinfo.AckSystemTime buildParsed()
          throws com.google.protobuf.InvalidProtocolBufferException {
        ProtoMsgData.Userinfo.AckSystemTime result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(
            result).asInvalidProtocolBufferException();
        }
        return result;
      }
      
      public ProtoMsgData.Userinfo.AckSystemTime buildPartial() {
        ProtoMsgData.Userinfo.AckSystemTime result = new ProtoMsgData.Userinfo.AckSystemTime(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.time_ = time_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }
      
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof ProtoMsgData.Userinfo.AckSystemTime) {
          return mergeFrom((ProtoMsgData.Userinfo.AckSystemTime)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }
      
      public Builder mergeFrom(ProtoMsgData.Userinfo.AckSystemTime other) {
        if (other == ProtoMsgData.Userinfo.AckSystemTime.getDefaultInstance()) return this;
        if (other.hasTime()) {
          setTime(other.getTime());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }
      
      public final boolean isInitialized() {
        if (!hasTime()) {
          
          return false;
        }
        return true;
      }
      
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder(
            this.getUnknownFields());
        while (true) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              this.setUnknownFields(unknownFields.build());
              onChanged();
              return this;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                this.setUnknownFields(unknownFields.build());
                onChanged();
                return this;
              }
              break;
            }
            case 8: {
              bitField0_ |= 0x00000001;
              time_ = input.readUInt64();
              break;
            }
          }
        }
      }
      
      private int bitField0_;
      
      // required uint64 time = 1;
      private long time_ ;
      public boolean hasTime() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      public long getTime() {
        return time_;
      }
      public Builder setTime(long value) {
        bitField0_ |= 0x00000001;
        time_ = value;
        onChanged();
        return this;
      }
      public Builder clearTime() {
        bitField0_ = (bitField0_ & ~0x00000001);
        time_ = 0L;
        onChanged();
        return this;
      }
      
      // @@protoc_insertion_point(builder_scope:ProtoMsgData.AckSystemTime)
    }
    
    static {
      defaultInstance = new AckSystemTime(true);
      defaultInstance.initFields();
    }
    
    // @@protoc_insertion_point(class_scope:ProtoMsgData.AckSystemTime)
  }
  
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_ProtoMsgData_UserInfo_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_ProtoMsgData_UserInfo_fieldAccessorTable;
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_ProtoMsgData_ReqCreateRole_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_ProtoMsgData_ReqCreateRole_fieldAccessorTable;
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_ProtoMsgData_AckUserInfo_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_ProtoMsgData_AckUserInfo_fieldAccessorTable;
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_ProtoMsgData_AckSystemTime_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_ProtoMsgData_AckSystemTime_fieldAccessorTable;
  
  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\016userinfo.proto\022\014ProtoMsgData\032\016business" +
      ".proto\032\014notice.proto\"\343\001\n\010UserInfo\022\016\n\006cha" +
      "rid\030\001 \002(\004\022\017\n\007account\030\002 \002(\t\022\r\n\005level\030\003 \002(" +
      "\r\022\020\n\010vouchers\030\004 \002(\r\022\017\n\007balance\030\005 \002(\r\022.\n\013" +
      "addressinfo\030\006 \003(\0132\031.ProtoMsgData.Address" +
      "Info\022*\n\torderform\030\007 \003(\0132\027.ProtoMsgData.O" +
      "rderForm\022(\n\006notice\030\010 \003(\0132\030.ProtoMsgData." +
      "NoticeInfo\"\017\n\rReqCreateRole\"7\n\013AckUserIn" +
      "fo\022(\n\010userinfo\030\001 \002(\0132\026.ProtoMsgData.User" +
      "Info\"\035\n\rAckSystemTime\022\014\n\004time\030\001 \002(\004"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
      new com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner() {
        public com.google.protobuf.ExtensionRegistry assignDescriptors(
            com.google.protobuf.Descriptors.FileDescriptor root) {
          descriptor = root;
          internal_static_ProtoMsgData_UserInfo_descriptor =
            getDescriptor().getMessageTypes().get(0);
          internal_static_ProtoMsgData_UserInfo_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_ProtoMsgData_UserInfo_descriptor,
              new java.lang.String[] { "Charid", "Account", "Level", "Vouchers", "Balance", "Addressinfo", "Orderform", "Notice", },
              ProtoMsgData.Userinfo.UserInfo.class,
              ProtoMsgData.Userinfo.UserInfo.Builder.class);
          internal_static_ProtoMsgData_ReqCreateRole_descriptor =
            getDescriptor().getMessageTypes().get(1);
          internal_static_ProtoMsgData_ReqCreateRole_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_ProtoMsgData_ReqCreateRole_descriptor,
              new java.lang.String[] { },
              ProtoMsgData.Userinfo.ReqCreateRole.class,
              ProtoMsgData.Userinfo.ReqCreateRole.Builder.class);
          internal_static_ProtoMsgData_AckUserInfo_descriptor =
            getDescriptor().getMessageTypes().get(2);
          internal_static_ProtoMsgData_AckUserInfo_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_ProtoMsgData_AckUserInfo_descriptor,
              new java.lang.String[] { "Userinfo", },
              ProtoMsgData.Userinfo.AckUserInfo.class,
              ProtoMsgData.Userinfo.AckUserInfo.Builder.class);
          internal_static_ProtoMsgData_AckSystemTime_descriptor =
            getDescriptor().getMessageTypes().get(3);
          internal_static_ProtoMsgData_AckSystemTime_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_ProtoMsgData_AckSystemTime_descriptor,
              new java.lang.String[] { "Time", },
              ProtoMsgData.Userinfo.AckSystemTime.class,
              ProtoMsgData.Userinfo.AckSystemTime.Builder.class);
          return null;
        }
      };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          ProtoMsgData.Business.getDescriptor(),
          ProtoMsgData.Notice.getDescriptor(),
        }, assigner);
  }
  
  // @@protoc_insertion_point(outer_class_scope)
}
