#flyer   20160-21-05 测试
DROP TABLE IF EXISTS test;
CREATE TABLE IF NOT EXISTS test
(
    `id`  BIGINT(20) UNSIGNED NOT NULL AUTO_INCREMENT,
    `charid` BIGINT(20) UNSIGNED,
    PRIMARY KEY(id)
) ENGINE=MyISAM DEFAULT CHARSET=utf8;

