#pragma once

#include "Protocol.h"

#define SERVICE_PROTOCOL_GROUP 0x1001

#define MSG_SERVICE_OPEN_REQUEST			MAKE_MSG_TYPE(SERVICE_PROTOCOL_GROUP, 0x0001)
#define MSG_SERVICE_OPEN_RESPONSE			MAKE_MSG_TYPE(SERVICE_PROTOCOL_GROUP, 0x0002)
#define MSG_SERVICE_CONNECT_ACT				MAKE_MSG_TYPE(SERVICE_PROTOCOL_GROUP, 0x0003)
#define MSG_SERIVCE_CLOSE_REQUEST			MAKE_MSG_TYPE(SERVICE_PROTOCOL_GROUP, 0x0004)
#define MSG_SERIVCE_CLOSE_RESPONSE			MAKE_MSG_TYPE(SERVICE_PROTOCOL_GROUP, 0x0005)
#define MSG_SERVICE_HEARTBREAK				MAKE_MSG_TYPE(SERVICE_PROTOCOL_GROUP, 0x0006)
#define MSG_SERVICE_CREATE					MAKE_MSG_TYPE(SERVICE_PROTOCOL_GROUP, 0x0007)
#define MSG_SERVICE_INFO_QUERY				MAKE_MSG_TYPE(SERVICE_PROTOCOL_GROUP, 0x0008)
#define MSG_SERVICE_INFO_ANSWER				MAKE_MSG_TYPE(SERVICE_PROTOCOL_GROUP, 0x0009)
//#define MSG_SERVICE_PEER_INIT_REQUEST		MAKE_MSG_TYPE(SERVICE_PROTOCOL_GROUP, 0x000a)
//#define MSG_SERVICE_PEER_INIT_RESPONSE		MAKE_MSG_TYPE(SERVICE_PROTOCOL_GROUP, 0x000b)

typedef struct tagMsgServiceInfo
{
	ACE_UINT32 unServiceID;
	ACE_UINT32 unIP;
	ACE_UINT32 unPort;
}MsgServiceInfo;

typedef struct tagMsgCreateService
{
	ACE_UINT32 unServiceType;
	ACE_UINT32 unServiceID;
	ACE_UINT32 unCallerServiceID;
}MsgCreateService;

typedef struct tagMsgServiceTimer
{
	long lTimerID;
}MsgServiceTimer;

/*
typedef struct tagMsgServicePeerInitRequest
{
	bool bInit;
	ACE_UINT32 unSendSN;
}MsgServicePeerInitRequest;

typedef struct tagMsgServicePeerInitResponse
{
	bool shouldReset;
}MsgServicePeerInitResponse;
*/

/*
#define MSG_SERVICE_OBJ_NOTFOUND			MAKE_MSG_TYPE(SERVICE_PROTOCOL_GROUP, 0x000a)
#define MSG_SERVICE_OBJ_MSG_REACHED			MAKE_MSG_TYPE(SERVICE_PROTOCOL_GROUP, 0x000b)
#define MSG_SERVICE_QUERY_OBJ_LOCATION		MAKE_MSG_TYPE(SERVICE_PROTOCOL_GROUP, 0x000c)
#define MSG_SERVICE_ANSWER_OBJ_LOCATION		MAKE_MSG_TYPE(SERVICE_PROTOCOL_GROUP, 0x000d)
#define MSG_SERVICE_UPDATE_OBJ_LOCATION		MAKE_MSG_TYPE(SERVICE_PROTOCOL_GROUP, 0x000e)
#define MSG_SERVICE_REMOVE_OBJ_LOCATION		MAKE_MSG_TYPE(SERVICE_PROTOCOL_GROUP, 0x000f)

typedef struct tagMsgObjNotfound
{
	ACE_UINT64 unObjID;
}MsgObjNotfound;

typedef struct tagMsgObjReached
{
	ACE_UINT64 unObjID;
}MsgObjReached;

typedef struct tagMsgQueryObjLocation
{
	ACE_UINT64 unObjID;
}MsgQueryObjLocation;

typedef struct tagMsgAnswerObjLocation
{
	ACE_UINT32 unServiceID;
	ACE_UINT64 unObjID;
}MsgAnswerObjLocation;

typedef struct tagMsgUpdateObjLocation
{
	ACE_UINT64 unObjID;
	ACE_UINT32 unServiceID;
	ACE_UINT32 unTimeStamp;
}MsgUpdateObjLocation;

typedef struct tagMsgRemoveObjLocation
{
	ACE_UINT64 unObjID;
	ACE_UINT32 unTimeStamp;
}MsgRemoveObjLocation;
*/

#define MSG_SERVICE_OBJ_UNREACHABLE					MAKE_MSG_TYPE(SERVICE_PROTOCOL_GROUP, 0x000c)
#define MSG_SERVICE_OBJ_MSG_REACHED					MAKE_MSG_TYPE(SERVICE_PROTOCOL_GROUP, 0x000d)
#define MSG_SERVICE_QUERY_OBJ_LOCATION				MAKE_MSG_TYPE(SERVICE_PROTOCOL_GROUP, 0x000e)
#define MSG_SERVICE_ANSWER_OBJ_LOCATION				MAKE_MSG_TYPE(SERVICE_PROTOCOL_GROUP, 0x000f)//Ó¦´ðÏûÏ¢
#define MSG_SERVICE_WANNA_CREATE_SERVICE_OBJ		MAKE_MSG_TYPE(SERVICE_PROTOCOL_GROUP, 0x0010)
#define MSG_SERVICE_WANNA_DESTROY_SERVICE_OBJ		MAKE_MSG_TYPE(SERVICE_PROTOCOL_GROUP, 0x0011)
#define MSG_SERVICE_CREATE_SERVICE_OBJ				MAKE_MSG_TYPE(SERVICE_PROTOCOL_GROUP, 0x0012)
#define MSG_SERVICE_DESTROY_SERVICE_OBJ				MAKE_MSG_TYPE(SERVICE_PROTOCOL_GROUP, 0x0013)
#define MSG_SERVICE_CREATE_SERVICE_OBJ_RESULT		MAKE_MSG_TYPE(SERVICE_PROTOCOL_GROUP, 0x0014)
#define MSG_SERVICE_DESTROY_SERVICE_OBJ_RESULT		MAKE_MSG_TYPE(SERVICE_PROTOCOL_GROUP, 0x0015)

typedef struct tagMsgServiceObjInfo
{
	ACE_UINT32 unAdapterID;
	ACE_UINT32 unObjID;
}MsgServiceObjInfo;

typedef struct tagMsgServiceObjLoaction
{
	ACE_UINT32 unServiceID;
	ACE_UINT32 unAdapterID;
	ACE_UINT32 unObjID;
	ACE_UINT32 unFlag;
}MsgServiceObjLoaction;

typedef struct tagMsgServiceObjOP
{
	ACE_UINT32 unAdapterID;
	ACE_UINT32 unObjID;
	ACE_UINT32 unSN;
	int nResult;
}MsgServiceObjOP;

#define MSG_SERVICE_CONSOLE_CMD				MAKE_MSG_TYPE(SERVICE_PROTOCOL_GROUP, 0x0020)

#define MAX_CONSOLE_CMD_LENGTH				256

typedef struct tagMsgConsoleCmd
{
	char cmd[MAX_CONSOLE_CMD_LENGTH];
}MsgConsoleCmd;

#define MSG_SERVICE_DB_HANDLER_NOTIFY		MAKE_MSG_TYPE(SERVICE_PROTOCOL_GROUP, 0x0021)

#define MSG_CREATE_BASE_OBJ					MAKE_MSG_TYPE(SERVICE_PROTOCOL_GROUP, 0x0101)
#define MSG_REMOVE_BASE_OBJ					MAKE_MSG_TYPE(SERVICE_PROTOCOL_GROUP, 0x0102)
#define MSG_CREATE_BASE_ADAPTER				MAKE_MSG_TYPE(SERVICE_PROTOCOL_GROUP, 0x0103)
#define MSG_REMOVE_BASE_ADAPTER				MAKE_MSG_TYPE(SERVICE_PROTOCOL_GROUP, 0x0104)

typedef struct tagMsgServiceObjOpArg
{
	ACE_UINT32 unID;
}MsgServiceObjOpArg;

#define MSG_SERVICE_STOP_SERVICE			MAKE_MSG_TYPE(SERVICE_PROTOCOL_GROUP, 0x0022)



/*
#define MSG_SERVICE_OBJ_DB_LOAD_REQUEST				MAKE_MSG_TYPE(SERVICE_PROTOCOL_GROUP, 0x0201)
#define MSG_SERVICE_OBJ_DB_LOAD_RESPONSE			MAKE_MSG_TYPE(SERVICE_PROTOCOL_GROUP, 0x0202)
#define MSG_SERVICE_OBJ_DB_SAVE_REQUEST				MAKE_MSG_TYPE(SERVICE_PROTOCOL_GROUP, 0x0203)
#define MSG_SERVICE_OBJ_DB_SAVE_RESPONSE			MAKE_MSG_TYPE(SERVICE_PROTOCOL_GROUP, 0x0204)


typedef struct tagMsgDBRequest
{
	ACE_UINT32 unType;
	ACE_UINT32 unSN;
	ACE_UINT32 unSize;
	char data[1];
}MsgDBRequest;

typedef struct tagMsgDBResponse
{
	ACE_UINT32 unType;
	ACE_UINT32 unSN;
	ACE_INT32 unRet;
	ACE_UINT32 unSize;
	char data[1];
}MsgDBResponse;
*/


#define MSG_SERVICE_STARTUP							MAKE_MSG_TYPE(SERVICE_PROTOCOL_GROUP, 0x0301)
#define MSG_SERVICE_SHUTDOWN						MAKE_MSG_TYPE(SERVICE_PROTOCOL_GROUP, 0x0302)
#define MSG_SERVICE_INIT_REQUEST					MAKE_MSG_TYPE(SERVICE_PROTOCOL_GROUP, 0x0303)
#define MSG_SERVICE_INIT_RESPONSE					MAKE_MSG_TYPE(SERVICE_PROTOCOL_GROUP, 0x0303)
#define MSG_SERVICE_INIT_DONE						MAKE_MSG_TYPE(SERVICE_PROTOCOL_GROUP, 0x0304)
#define MSG_SERVICE_CLOSED							MAKE_MSG_TYPE(SERVICE_PROTOCOL_GROUP, 0x0305)

typedef struct tagMsgServiceStartup
{
	ACE_UINT32 unParentID;
	ACE_UINT32 unType;
	ACE_UINT32 unSize;
	char arg[1];
}MsgServiceStartup;

typedef struct tagMsgServiceShutdown
{
	ACE_UINT32 unSize;
	char arg[1];
}MsgServiceShutdown;

